Remove remains of the old bat gui tool
bareos/bareos pull request #1012
Opened 2021-12-05 13:46 UTC by tuxmaster5000

### Thank you for contributing to the Bareos Project!
I have found some rests of the old bar gui tool

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-12-07 16:53 UTC, joergsteffens requested changes
Thank you for your contribution. You're absolutely right to remove references to bat. However, I'd prefer the documentation section to stay. Would you adapt your PR accordingly?

2021-12-07 16:53 UTC, joergsteffens commented on docs/manuals/images/image_scales
> -bat_icon.png 0.65000
I'm pretty sure, this file can be removed completely.

2021-12-07 16:53 UTC, joergsteffens commented on docs/manuals/source/Appendix/BareosPrograms.rst
> -
While I understand the reasoning about removing this section, I'd prefer this section to stay. If somebody is wondering why he does not find bar, the documentation should show hin the reason.

2021-12-08 06:13 UTC, tuxmaster5000 commented
I have done the modifications (hopefully) all. :)

2021-12-09 08:11 UTC, joergsteffens commented
Oh, I fear there has been a mismatch of versions or branches. The second commit mess up some other sections. Either you can clean this or I'll take a look at this, probably next week.
One other thing: when this is done, I'd prefer a single commit (commit message of the first commit is fine).

2021-12-09 08:24 UTC, tuxmaster5000 commented
This have time, so you can do this next week. Its only an cosmetic "problem".

2021-12-18 16:42 UTC, joergsteffens commented on docs/manuals/images/image_scales
> -bat_icon.png 0.65000
File removed.

2021-12-18 16:42 UTC, joergsteffens commented on docs/manuals/source/Appendix/BareosPrograms.rst
> -
Readded section

2021-12-18 16:43 UTC, joergsteffens approved these changes

2021-12-21 08:48 UTC, merged