webui: provide a restore support notification for NDMP backups
bareos/bareos pull request #1020
Opened 2021-12-09 16:27 UTC by fbergkemper

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-12-10 08:42 UTC, pstorz requested changes
Unfortunately webui:admin_restore test fails always.

2021-12-10 13:02 UTC, fbergkemper commented
> Unfortunately webui:admin_restore test fails always.

There was a misplaced early bsock->disconnect() call, that broke the final restore step. I've fixed and updated the PR. Also I've added another commit for the documentation.

2021-12-13 10:00 UTC, pstorz requested changes
PR Title is misleading. Better: 
webui: provice a notification that NDMP restores are NOT supported by webui.

Also please add a bit more info to the commit descriptions:

docs: add restore section limitations -> docs: add section that NDMP restores are not supported by webui.

webui: provide a restore support notification for NDMP backups -> webui: provide a notification that NDMP restores are not supported by webui. (Same as PR title)

2021-12-13 10:24 UTC, pstorz approved these changes
Looks good. If the build passes with all checks green we can merge.

2021-12-13 10:37 UTC, fbergkemper commented
> PR Title is misleading. Better: webui: provice a notification that NDMP restores are NOT supported by webui.
> 
> Also please add a bit more info to the commit descriptions:
> 
> docs: add restore section limitations -> docs: add section that NDMP restores are not supported by webui.
> 
> webui: provide a restore support notification for NDMP backups -> webui: provide a notification that NDMP restores are not supported by webui. (Same as PR title)

Done

2021-12-13 12:11 UTC, merged