webui: fix routing issue with client names that contain dots
bareos/bareos pull request #1023
Opened 2021-12-14 14:17 UTC by fbergkemper

This PR fixes a routing issues with client names that contain dots.

We now use query parameters for the link generation instead of
a route segment.

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-12-15 11:28 UTC, pstorz requested changes
Good work, However, I think it would make sense to change the PR name to better describe what problem was fixed (From a user point of view)

e.g. webui: client details now can be displayed for client names containing dots.

Also the PR Number i missing in CHANGELOG.md

2021-12-15 11:28 UTC, pstorz commented on CHANGELOG.md
> +- webui: fix routing issue with client names that contain dots
PR number is missing

2021-12-15 11:49 UTC, fbergkemper commented on CHANGELOG.md
> +- webui: fix routing issue with client names that contain dots
Added

2021-12-15 11:51 UTC, fbergkemper commented
> Good work, However, I think it would make sense to change the PR name to better describe what problem was fixed (From a user point of view)
> 
> e.g. webui: client details now can be displayed for client names containing dots.
> 

PR subject changed to better describe the fix from user POV.

2021-12-16 12:30 UTC, pstorz approved these changes
Good work!

2021-12-16 12:30 UTC, merged