Python plugins: add default module_path to search path
bareos/bareos pull request #1038
Opened 2021-12-23 09:58 UTC by joergsteffens

Currently all Python modules get installed to the plugin directory.
However, every plugin configuration requires the parameter module_path set to this value.

This PR adds the Python Plugin module path to the default search path, so that specifying the module_path is only unnecessary in non-standard installations.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2022-01-26 11:36 UTC, pstorz reviewed
Checked first commit and the changes look good to me.
Good work!

2022-01-28 18:51 UTC, sduehr requested changes
Thanks a lot, only found some typos.

2022-01-28 18:51 UTC, sduehr commented on core/src/plugins/filed/python/python-fd.cc
> +  "  Additional parameter are plugin specific."
```suggestion
  "  Additional parameters are plugin specific."
```

2022-01-28 18:51 UTC, sduehr commented on core/src/plugins/stored/python/python-sd.cc
> +  "  Additional parameter are plugin specific."
```suggestion
  "  Additional parameters are plugin specific."
```

2022-01-28 18:51 UTC, sduehr commented on docs/manuals/source/Appendix/Howtos.rst
> +         #         ":mysqluser=bareos
```suggestion
         #         ":mysqluser=bareos"
```

2022-01-28 18:51 UTC, sduehr commented on docs/manuals/source/DeveloperGuide/PythonPluginAPI.rst
> +      While the c++ code and the Python api have been reorganized, the Python
```suggestion
      While the C++ code and the Python api have been reorganized, the Python
```

2022-01-28 18:51 UTC, sduehr commented on docs/manuals/source/TasksAndConcepts/Plugins/DirectorPlugins/PythonDirPlugin.rst.inc
> +-  activate the plugin in the Bareos Director configuration (:config:option:`dir/director/PluginNames`)
```suggestion
-  activate the plugin in the |dir| configuration (:config:option:`dir/director/PluginNames`)
```

2022-01-28 18:51 UTC, sduehr commented on docs/manuals/source/TasksAndConcepts/Plugins/DirectorPlugins/PythonDirPlugin.rst.inc
> +The class-based approach lets you easily reuse stuff already defined in the Python base class,
```suggestion
The class-based approach lets you easily reuse code already defined in the Python base class,
```

2022-01-28 18:51 UTC, sduehr commented on docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
> +         Plugin = "pytho3n"
```suggestion
         Plugin = "python3"
```

2022-02-02 14:25 UTC, joergsteffens commented
@sduehr thank you for your suggestions. I've applied them and then rebased them on master, because of a merge conflict. It would be great, if you can review this PR again. Also 5 check-marks are not set. Do you request changes from my side?

2022-02-02 14:30 UTC, joergsteffens commented
@sduehr one additional thing to consider is if it is appropriate to update the Python plugins version numbers from 4 to 5. Currently for all 3 Python plugins is is defined as:
```
#define PLUGIN_DATE "May 2020"
#define PLUGIN_VERSION "4"
```

2022-02-07 19:59 UTC, merged