docs: split plugin file into chapter files
bareos/bareos pull request #1046
Opened 2022-01-14 15:40 UTC by DjamilaMamedov

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2022-01-17 11:41 UTC, joergsteffens commented on CHANGELOG.md
> +-split plugin file into chapter files, removed wrong includes, created a file for each Plugin[PR #1046]
```suggestion
- split the very long `Plugins.rst` file into one file per Bareos plugin [PR #1046]
```

2022-01-17 15:43 UTC, bruno-at-bareos requested changes
I've made some suggestion to also fix all index syntax to use the sphinx one.
I think that mariadbplugin.rst can be remove as it serve nothing useful.

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins.rst
> +
```suggestion

.. include:: Plugins/DirectorPlugins.rst.inc
.. include:: Plugins/FileDaemonPlugins.rst.inc 
.. include:: Plugins/StorageDaemonPlugins.rst.inc
```
Better to keep Director first, as it is a logical follow up of Python.

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins.rst.inc
> +.. include:: Plugins/FileDaemonPlugins/MariaDBPlugin.rst.inc
```suggestion

```

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins.rst.inc
> +.. include:: Plugins/FileDaemonPlugins/MariaDBPlugin.rst.inc
```suggestion

```
There's nothing useful inside it, Corresponding file should be removed

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/MariaDBPlugin.rst.inc
> +MariaDB Plugin
This file need to be removed, nothing useful in.

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/StorageDaemonPlugins/AutoxflateSd.rst.inc
> +:index:`\ <single: Plugin; autoxflate-sd>`\
```suggestion
.. index::
   single: Plugin; autoxflate-sd
```

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/StorageDaemonPlugins/PythonSdPlugin.rst.inc
> +:index:`\ <single: Plugin; Python; Storage Daemon>`\
```suggestion
.. index::
   single: Plugin; Python; Storage Daemon
```
Use sphinx syntax for index

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/StorageDaemonPlugins/ScsicryptoSd.rst.inc
> +:index:`\ <single: Plugin; scsicrypto-sd>`\
```suggestion
.. index::
   single: Plugin; scsicrypto-sd
```

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/StorageDaemonPlugins/ScsitapealertSd.rst.inc
> +:index:`\ <single: Plugin; scsitapealert-sd>`\
```suggestion
.. index::
   single: Plugin; scsitapealert-sd
```

2022-01-17 15:43 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/Plugins/DirectorPlugins/PythonDirPlugin.rst.inc
> +:index:`\ <single: Plugin; Python; Director>`\
```suggestion
.. index::
   single: Plugin; Python; Director
```

2022-01-18 09:01 UTC, bruno-at-bareos requested changes
There's still some needed changes, as I found some mispelled lower/upper case name in plugin file name.
The following files need to be renamed.
Problem with lower/upper case name of split plugin files

- docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/GlusterFsPlugin.rst.inc -> GlusterFSPlugin.rst.inc
- docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/LdapPlugin.rst.inc -> LDAPPlugin.rst.inc
- docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/MsSqlPlugin.rst.inc -> MSSqlPlugin.rst.inc
- docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/MySqlPlugin.rst.inc -> MySQL.rst.inc
- docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PostgreSqlPlugin.rst.inc -> PostgreSQLPlugin.rst.inc

2022-01-18 13:39 UTC, bruno-at-bareos approved these changes
The build doc fail actually and that need to be fixed.

2022-01-18 16:26 UTC, joergsteffens approved these changes

2022-01-18 16:39 UTC, merged