ndmp: avoid isilon 9.1.0.0 'Invalid nlist.tape_offset -1' error
bareos/bareos pull request #1049
Opened 2022-01-18 13:22 UTC by pstorz

The isilon 9.1.0.0 release seems to have added a sanity check in ndmp
that checks that the tape offsets are on 512B boundaries.

The following error is issued when a restore is triggered to a isilon
9.1.0.0 system:

  'Invalid nlist.tape_offset -1 at index 1 - tape offset not aligned at 512B boundary'

However, -1 is an allowed value (NDMP_INVALID_U_QUAD) and was accepted
on every NDMP implementation we tested against including older isilon
versions.

To fix the problem, the isilon needs to check for NDMP_INVALID_U_QUAD
before it checks for the 512B boundary to fix the problem.

Otherwise we could enable this workaround depending on a new
configuration option.

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2022-01-18 13:33 UTC, bruno-at-bareos requested changes
I've made the suggestion for having the default value for the documentation.

2022-01-18 13:33 UTC, bruno-at-bareos commented on core/src/dird/dird_conf.cc
> +  { "NdmpNamelistFhinfoSetZeroForInvalidUquad", CFG_TYPE_BOOL, ITEM(res_dir, ndmp_fhinfo_set_zero_for_invalid_u_quad), 0, 0, NULL, "21.0.1-", NULL },
```suggestion
  { "NdmpNamelistFhinfoSetZeroForInvalidUquad", CFG_TYPE_BOOL, ITEM(res_dir, ndmp_fhinfo_set_zero_for_invalid_u_quad), 0, CFG_ITEM_DEFAULT, "false", "21.0.1-", NULL },
```

2022-02-03 13:27 UTC, bruno-at-bareos submitted a review, later dismissed
Please check the proposal suggestions, (version change to 20.0.6 due to backport)
Also add a CHANGELOG entry.

2022-02-03 13:27 UTC, bruno-at-bareos commented on docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
> +          "versions": "21.0.1-"
```suggestion
          "versions": "20.0.6-"
```

2022-02-04 11:26 UTC, arogge approved these changes

2022-02-04 11:31 UTC, merged