jstreegrid: remove handling of IE < 8 using navigator interface
bareos/bareos pull request #1140
Opened 2022-03-25 12:31 UTC by fbergkemper

Starting in Chrome 101, the amount of information available in the
User Agent string will be reduced.

This PR just comments out the specific handling of IE < 8,
to avoid issues in Chrome >= 101.

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-03-25 13:00 UTC, pstorz requested changes
The title should contain the reason why we remove that support.. 

Why not simply remove the code in question without extra comment? 
E8 is alread 13 years old and only running on OS that are not supported anymore.

2022-03-25 13:12 UTC, fbergkemper commented on CHANGELOG.md
> +- jstreegrid: remove handling of IE < 8 using navigator interface [PR #1140]
Sure, the subject could have been a bit more precise. Applied your suggestion.

2022-03-25 13:18 UTC, fbergkemper commented
> Why not simply remove the code in question without extra comment? E8 is alread 13 years old and only running on OS that are not supported anymore.

It's IE < 8, which I would think nobody should use nowadays, totally agree with you. However, I kept it for now commented out in case of an upstream change of the extension, so I remember what is going on and don't re-introduce by accident.

2022-03-25 13:44 UTC, pstorz commented
> It's IE < 8, which I would think nobody should use nowadays, totally agree with you. However, I kept it for now commented out in case of an upstream change of the extension, so I remember what is going on and don't re-introduce by accident.

But that is what git is for, isn't it?

2022-03-25 14:04 UTC, fbergkemper commented
> > It's IE < 8, which I would think nobody should use nowadays, totally agree with you. However, I kept it for now commented out in case of an upstream change of the extension, so I remember what is going on and don't re-introduce by accident.
> 
> But that is what git is for, isn't it?

I'd like to have a clear hint, but I'm going to remove the code section.
It's not worth a discussion, let's get this done.

2022-03-29 11:41 UTC, pstorz approved these changes

2022-03-29 11:42 UTC, merged