Bareos Python Plugins: fix handling of extra pluginoptions
bareos/bareos pull request #1177
Opened 2022-05-06 15:53 UTC by joergsteffens

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-05-16 10:07 UTC, pstorz requested changes
I have the following change requests:
* The problem that is fixed with this PR is not described
* Variable name enhancements
* changelog.md entry is missing
* bareos-check-sources is not happy about systemtests/python-modules/bareos_unittest/json.py, needs to be formatted
* system:python-bareos:python_fd_plugins does not pass:
```
361: === python-bareos/test_python_fd_plugins: starting at 12:05:14 ===
361: =
361: =
361: /home/pstorz/git/PR-REVIEW/python-bareos/bareos/bsock/lowlevel.py:57: UserWarning: Connection encryption via TLS-PSK is not available, as the module sslpsk is not installed.
361:   warnings.warn(
361: test_additional_pluginoptions (test_python_fd_plugins.BareosFdPythonPluginOptions) ... FAIL
361: test_overwrite_pluginoptions (test_python_fd_plugins.BareosFdPythonPluginOptions)
361: Overwrites a plugin option ... expected failure
361: test_without_extra_pluginoptions (test_python_fd_plugins.BareosFdPythonPluginOptions) ... FAIL
361: 
361: ======================================================================
361: FAIL: test_additional_pluginoptions (test_python_fd_plugins.BareosFdPythonPluginOptions)
361: ----------------------------------------------------------------------
361: Traceback (most recent call last):
361:   File "/home/pstorz/git/PR-REVIEW/b/systemtests/tests/python-bareos/test_python_fd_plugins.py", line 89, in test_additional_pluginoptions
361:     jobid = self.run_job(
361:   File "/home/pstorz/git/PR-REVIEW/systemtests/python-modules/bareos_unittest/json.py", line 103, in run_job
361:     self.wait_job(director, jobId)
361:   File "/home/pstorz/git/PR-REVIEW/systemtests/python-modules/bareos_unittest/json.py", line 91, in wait_job
361:     self.assertEqual(result["job"]["jobstatuslong"], expected_status)
361: AssertionError: 'Fatal Error' != 'OK'
361: - Fatal Error
361: + OK
361: 
361: 
361: ======================================================================
361: FAIL: test_without_extra_pluginoptions (test_python_fd_plugins.BareosFdPythonPluginOptions)
361: ----------------------------------------------------------------------
361: Traceback (most recent call last):
361:   File "/home/pstorz/git/PR-REVIEW/b/systemtests/tests/python-bareos/test_python_fd_plugins.py", line 55, in test_without_extra_pluginoptions
361:     jobid = self.run_job(director, jobname, level="Full", wait=True)
361:   File "/home/pstorz/git/PR-REVIEW/systemtests/python-modules/bareos_unittest/json.py", line 103, in run_job
361:     self.wait_job(director, jobId)
361:   File "/home/pstorz/git/PR-REVIEW/systemtests/python-modules/bareos_unittest/json.py", line 91, in wait_job
361:     self.assertEqual(result["job"]["jobstatuslong"], expected_status)
361: AssertionError: 'Fatal Error' != 'OK'
361: - Fatal Error
361: + OK
361: 
361: 
361: ----------------------------------------------------------------------
361: Ran 3 tests in 6.685s
361: 
361: FAILED (failures=2, expected failures=1)
361: ERROR: 
361: ERROR: 
361:  
361:   !!!!! python-bareos/test_python_fd_plugins failed!!! 12:05:21 !!!!! 
361:    Status: estat=9 zombie=0 backup=0 restore=0 diff=0
361:  
2/3 Test #361: system:python-bareos:python_fd_plugins ...***Failed    6.94 sec
```

2022-05-17 08:03 UTC, pstorz requested changes
I have the following remarks:
- The Pluginoptions are in one line in the docs, while the multiline is much better readable.
- Last build failed, now waiting for next build.

2022-05-17 08:18 UTC, joergsteffens commented on docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
> +   "python:module_name=bareos-fd-vmware:dc=dass5:folder=/:vmname=stephand-test02:vcserver=virtualcenter5.dass-it:vcuser=bakadm@vsphere.local:vcpass=Bak.Adm-1234:localvmdk=yes"
This is a string that has to be typed during the restore command. I assume, splitting it over multiple lines is not an option, especially not in Bareos <= 15.2.3, as stated above.
But now that you point to it, I think, also the quoted around this string have to be removed.

2022-05-18 09:04 UTC, pstorz approved these changes

2022-05-18 09:05 UTC, merged