Add support for Ubuntu 22.04
bareos/bareos pull request #1179
Opened 2022-05-11 08:07 UTC by pstorz

This PR enables buliding for Ubuntu 22.04

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-06-21 15:01 UTC, bruno-at-bareos requested changes
Mostly okay, see proposal for the suse gcc block in spec.

2022-06-22 07:46 UTC, bruno-at-bareos commented
During the review, the check-sources return modification on 
```

2022-06-22 09:35 UTC, pstorz commented on core/platforms/packaging/bareos.spec
>  BuildRequires: gcc9
As we talked, we do not want to change the compiler of a bareos release for a specific OS release.

2022-06-22 10:03 UTC, bruno-at-bareos commented on CHANGELOG.md
> +- build: Add support for Ubuntu 22.04, Fedora 36, EL 9, openSUSE 15.4
```suggestion
- build: Add support for Ubuntu 22.04, Fedora 36, EL 9, openSUSE 15.4 [PR #1179]
```

2022-06-22 12:28 UTC, bruno-at-bareos approved these changes
After last green, the PR is ready to be merged. Thanks for the work.

2022-06-22 12:46 UTC, merged