doc: Add Security FIPS section
bareos/bareos pull request #1181
Opened 2022-05-11 15:09 UTC by bruno-at-bareos

This PR add a section to explain how to setup and check FIPS enabled computer.
backport should be limited to 21 version as only newer enterprise OS are concerned.

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-07-28 10:25 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +To be able to run successfully Bareos in `FIPS` mode so adjustment need to be made.
```suggestion
To be able to run Bareos in `FIPS` mode some adjustment need to be made.
```

2022-07-28 10:25 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +but those rules should apply also to derivative like CentOS, openSUSE.
```suggestion
but those rules should apply also to derivative like CentOS or openSUSE.
```

2022-07-28 10:25 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +if you see error log like
```suggestion
if you see errors log like:
```

2022-07-28 10:25 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +You will have to change the Signature option in you fileset to something stronger that MD5 or SHA1.
```suggestion
You will have to change the **Signature** option in you fileset to something stronger than MD5 or SHA1, for example **SHA256**:
```

2022-07-28 10:25 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-security-fips.html
```suggestion
https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-security-fips.html
```

2022-07-28 10:25 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +:strong:`beware of Signature option` all MD5 related function are disabled in `FIPS` mode.
:```suggestion
:strong:`Beware of  the fileset *Signature* option.` All MD5 related function are disabled in `FIPS` mode.
```

2022-07-28 10:42 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +crypto.fips_enabled = 0 shows that fips is not running. If crypto.fips_enabled = 1, then fips is running.
```suggestion
**crypto.fips_enabled = 0** shows that fips is not running. If **crypto.fips_enabled = 1**, then fips is running.
```

2022-07-28 10:45 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +:strong:`FIPS` acronym stand for Federal Information Processing Standards.
```suggestion
The acronym :strong:`FIPS` stands for Federal Information Processing Standards.
```

2022-07-28 10:48 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +a) Ensure fips_enabled is on
```suggestion
1. Ensure fips_enabled is on
```

2022-07-28 10:54 UTC, pstorz requested changes
I would suggest to move the "MD5 needs to be replaced by SHA256" to the end of the description. When trying to get bareos running on the fips machine, first the openssl needs to be fixed so that the daemons can even communicate, then the MD5 Problem pops up.

2022-07-28 10:54 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +b) Run openssl server part
```suggestion
2. Run openssl server part
```

2022-07-28 10:54 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +c) Run openssl client part
```suggestion
3. Run openssl client part
```

2022-07-28 10:54 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +d) Expected result, connection is established with a FIPS-140 2 compatible mechanism.
```suggestion
4. Expected result, connection is established with a FIPS-140 2 compatible mechanism.
```

2022-07-28 10:54 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +   OPENSSL_FORCE_FIPS_MODE=1 openssl s_client -tls1_3 -nocert -psk 1234567890
```suggestion
   OPENSSL_FORCE_FIPS_MODE=1 openssl s_client -tls1_3 -psk 1234567890
```

SLE 15 SP4 does not have "-nocert" in s_client

2022-07-28 11:34 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +:strong:`beware of Signature option` all MD5 related function are disabled in `FIPS` mode.
```suggestion
:strong:`beware of the fileset *Signature* option` all MD5 related function are disabled in `FIPS` mode.
```

2022-07-28 11:38 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
> +The above test procedure should work out of the box, and Bareos daemons should select only FIPS approved protocols.
```suggestion
For RedHat RHEL 9 follow the editor instructions located at:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/assembly_installing-the-system-in-fips-mode_security-hardening

The above test procedure should work out of the box, and Bareos daemons should select only FIPS approved protocols.
```

2022-08-01 08:49 UTC, pstorz approved these changes
Looks good!

2022-08-02 11:25 UTC, bruno-at-bareos commented
@pstorz can this one finished now and merged since approved, also check #1212 backport

2022-08-02 13:31 UTC, pstorz approved these changes
Good work!

2022-08-02 13:31 UTC, merged