docs: Fix broken links with sphinx linkchecker
bareos/bareos pull request #1200
Opened 2022-07-06 12:19 UTC by bruno-at-bareos

Documentation use sphinx linkcheck to fix broken links

- Adding linkcheck options to conf.py
- Fix all broken link in documentation

 Sphinx linkcheck can be used during documentation build

    ```sphinx-build -M linkcheck docs/manuals/source docs/BareosMainReference -j2```

The automatic usage during documentation build, still need to be discussed.

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-07-07 17:23 UTC, joergsteffens requested changes
I'm very glad you found and configured this tool.
I've suggestions on some of the internal URLs, but besides that, I'm fine with this PR.

2022-07-11 07:59 UTC, bruno-at-bareos commented on docs/manuals/source/DeveloperGuide/generaldevel.rst
> +We have a bug database which is at https://bugs.bareos.org/my_view_page.php.
Thanks for the pointer was a left over from applying all redirections, but we skip now bareos domain.

2022-07-11 08:00 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
> +You can use programs like `xca <https://www.hohnstaedt.de/xca/>`_ or TinyCA to easily manage your own CA with a Graphical User Interface.
Thanks nice suggestion.

2022-07-11 08:06 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/AutochangerSupport.rst
> +The `Bareos Whitepaper Tape Speed Tuning <https://www.bareos.com/wp-content/uploads/2021/05/optimizing-the-tape-speed.pdf>`_ shows that the two parameters :strong:`Maximum File Size`\  and :strong:`M
Nice, a lot better.

2022-07-11 10:07 UTC, joergsteffens approved these changes
Very nice!

2022-07-11 10:08 UTC, merged