[WIP] docs: overall cleanup
bareos/bareos pull request #1203
Opened 2022-07-07 13:42 UTC by bruno-at-bareos

This PR aims to cleanup our documentation and included some long awaited task.

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-08-11 13:54 UTC, bruno-at-bareos commented
@joergsteffens I would like to have your thoughts on the changes made here, especially about the still present table located at
[OperatingSystems](https://download.bareos.org/bareos/experimental/CD/PR-1203/BareosMainReference/Appendix/OperatingSystems.html#)

2022-08-12 15:10 UTC, joergsteffens reviewed
I left some initial remarks. If you which, I can also do a full review. However, I think it makes sense to split this PR.

Additional remarks:
* Install on Univention Corporate Server
  * Special Univention Corporate Server are no longer provided. Instead Debian packages should be used. Therefore this chapter should get replaced by a small hint, explaining this.
* I see that you updated the Debian install instructions, as required for newer versions of Debian. However it now even gets more complicated. I think we can make this a bit easier by providing more config files in our repository. To test this, it would make sense to split this in a seperate PR.
* I think the installation chapter should distinguish between server and client only installations. Maybe strictly splitting them in different chapters??? We can discuss this.
* While it is good that you added information for bareos.com customers, I think they still got it harder to find the required information. Maybe we find a way to make installation easier for them. Extra chapter for installing bareos.com? Of course, this would be partly redundant.

2022-08-15 07:54 UTC, bruno-at-bareos commented on docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
> +   # DIST=RHEL_9
Fixed, also there was several occurrence of EL_9.

2022-08-15 08:00 UTC, bruno-at-bareos commented on docs/manuals/source/Appendix/OperatingSystems.rst
>     RHEL,     current, v12.4, v12.4, v12.4
Updated

2022-08-15 08:01 UTC, bruno-at-bareos commented on docs/manuals/source/Appendix/OperatingSystems.rst
> +
Updated

2022-08-15 08:01 UTC, bruno-at-bareos commented on docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
> +For those who have a valid subscription contract, the repositories are located at https://download.bareos.org/bareos/release/.
updated

2022-08-22 14:03 UTC, joergsteffens requested changes
Besides of this we still got the topics:

- Keeping the "Installing Bareos" section separate between Bareos server and client only installations.
- Univention Corporate Server no longer with special integration. Section can be replaced with a hint about this and a hint about how to use UCS5
- Handling of Debian installations

2022-08-22 14:18 UTC, bruno-at-bareos commented on CHANGELOG.md
> +- update Appendix/HardwareSizing DB size with new numbers and formulas [BUG #1477][PR #1203]
Duplicate of PR #1231
```suggestion

```

2022-08-22 14:23 UTC, bruno-at-bareos commented on docs/manuals/source/Appendix/OperatingSystems.rst
I think the >=7 is the best solution, until Microsoft change something in VSS API.

2022-08-22 14:24 UTC, bruno-at-bareos commented on docs/manuals/source/Appendix/OperatingSystems.rst
> +                                            , 8/2012/7/2008/Vista, v12.4–v14.2
```suggestion
                                           , 2008/Vista/2003/XP, v12.4–v14.2
   :ref:`MS Windows <section-windows>` 64bit, >= 7, v12.4, v15.2, v15.2
                                            , 2008/Vista, v12.4–v14.2
```

2022-08-22 14:37 UTC, bruno-at-bareos commented
- Did you have example or suggestion for this topic "Univention Corporate Server no longer with special integration. Section can be replaced with a hint about this and a hint about how to use UCS5" ?
- For Debian once we have the internal new helper ready the section can be simplified
- About the split this is on the next dev meeting agenda

2022-08-22 14:43 UTC, bruno-at-bareos commented on CHANGELOG.md
> +- daemons: changed daemon CLI arguments parsing [PR #1187]
done in latest changes of CHANGELOG.md

2022-09-01 14:06 UTC, bruno-at-bareos commented
Waiting PR #1238 to be merged before restructuring further.

2022-09-29 07:53 UTC, bruno-at-bareos commented
The only changes missing (deleting docs/manuals/source/include/images/dbconfig-2-select-database-type.png) will be operated into a clean new PR.

2022-09-29 07:53 UTC, closed without merging