dird: fix odd-even weeks bug in schedule
bareos/bareos pull request #1210
Opened 2022-07-22 14:53 UTC by HediBenFraj

### Description

There is a bug where the config parser is not performing as expected when it comes to scheduling odd/even weeks

#### config files
Schedule {
  Name = "Odd Weeks"
  Run = w01/w02 sun at 23:10
}

Schedule {
  Name = "Even Weeks"
  Run = w00/w02 fri at 23:10
}

#### parsed schedule
show schedules
Schedule {
 Name = "Odd Weeks"
 Run = Sun w00,w02,w04,w06,w08,w10,w12,w14,w16,w18,w20,w22,w24,w26,w28,w30,w32,w34,w36,w38,w40,w42,w44,w46,w48,w50,w52 at 23:10
}

Schedule {
 Name = "Even Weeks"
 Run = Fri w01,w03,w05,w07,w09,w11,w13,w15,w17,w19,w21,w23,w25,w27,w29,w31,w33,w35,w37,w39,w41,w43,w45,w47,w49,w51 at 23:10
}

the odd and even weeks are flipped

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-07-25 07:54 UTC, pstorz requested changes
Good that you found the problem :However, the test you added does not check anything.

The test needs to really test that the functionality being tested works as expected.

2022-08-08 15:04 UTC, bruno-at-bareos requested changes
I let some comment into the code. Basically I think it will be more coherent to use the same schedule name as state into the documentation. This can be applied also to the test name.

About the change in itself, I would prefer that all the code we have for modulo keep its similarity.

2022-08-10 13:28 UTC, bruno-at-bareos approved these changes
I approve this changes, it even fix the 3rd example we have in the documentation.
```
Schedule {
  Name = "On the 3rd week in a 5-week-cycle"
  Run = w03/w05 at 23:10
}
```
Before this PR we obtain
```
Schedule {
  Name = "On the 3rd week in a 5-week-cycle"
  Run = w02,w07,w12,w17,w22,w27,w32,w37,w42,w47,w52 at 23:10
}
```
With this PR we start on week 3 then 8 (3+5) etc...
```
Schedule {
  Name = "On the 3rd week in a 5-week-cycle"
  Run = w03,w08,w13,w18,w23,w28,w33,w38,w43,w48,w53 at 23:10
}
```

2022-08-11 12:07 UTC, pstorz requested changes
See comments.

2022-08-11 12:07 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  ScheduleResource *resource_iterator = nullptr, *even_schedule = nullptr,
Please attach the * to the type, not to the variable.
Please define every variable in an own line which makes it much better readable.

2022-08-11 12:07 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  } while (resource_iterator->next_ != nullptr);
This whole loop probably can be replaced by two my_config->GetResWithName() calls.

2022-08-12 09:33 UTC, pstorz requested changes

2022-08-12 09:33 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  even_schedule = (directordaemon::ScheduleResource*)my_config->GetResWithName(
```suggestion
ScheduleResource*  even_schedule = (directordaemon::ScheduleResource*)my_config->GetResWithName(
```

2022-08-12 09:33 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  ScheduleResource* even_schedule = nullptr;
```suggestion
```

2022-08-12 09:33 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  ScheduleResource* odd_schedule = nullptr;
```suggestion
```

2022-08-12 09:33 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  odd_schedule = (directordaemon::ScheduleResource*)my_config->GetResWithName(
```suggestion
ScheduleResource*  odd_schedule = (directordaemon::ScheduleResource*)my_config->GetResWithName(
```

2022-08-12 09:33 UTC, pstorz commented on core/src/tests/test_config_parser_dir.cc
> +  odd_schedule = (directordaemon::ScheduleResource*)my_config->GetResWithName(
It is often the best way  to define and initialize a variable immediately before the first use.

2022-08-15 07:32 UTC, bruno-at-bareos approved these changes
Nice improvements.

2022-08-16 14:19 UTC, pstorz approved these changes
Good work!

2022-08-16 14:21 UTC, merged