Fix output of show command for RunsOnClient
bareos/bareos pull request #1217
Opened 2022-08-09 17:46 UTC by joergsteffens

This change fixes the output of the show command for RunsOnClient.

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-08-10 08:04 UTC, bruno-at-bareos commented
Hello Joerg, I've made some additional tests and I would like to clear out the unclear state of where the job will be run in the following scenario.

If defined like
```
  # Update stats run them on server.
  RunScript {
    Console = "prune stats yes"
    Console = "update stats days=3"
    Console = ".bvfs_update"
    RunsWhen = After
    RunsOnClient = no
  }
```
With this PR It will output the following
```
  RunScript {
    Console = "prune stats yes"
    RunsWhen = "after"
    RunsOnClient = No
  }
  RunScript {
    Console = "update stats days=3"
    RunsWhen = "after"
    RunsOnClient = No
  }
  RunScript {
    Console = ".bvfs_update"
    RunsWhen = "after"
    RunsOnClient = No
  }
```
Which is what we decide is correct.

Now if we don't specify Where it run like 
```
  # with no runsonclient
  RunScript {
    Console = "prune stats yes"
    Console = "update stats days=3"
    Console = ".bvfs_update"
    RunsWhen = After
  }
```
It shows
```
  RunScript {
    Console = "prune stats yes"
    RunsWhen = "after"
  }
  RunScript {
    Console = "update stats days=3"
    RunsWhen = "after"
  }
  RunScript {
    Console = ".bvfs_update"
    RunsWhen = "after"
  }
```
Which let undetermined if yes or no it will run on client, the operator can check the documentation and will find that by default ```RunOnClient = Yes```.
If it is easy to agree that console command will never been run on client, it is more complicated to determine if a command will be yes or no RunOnClient = yes.
To explain a bit more the uncertain state we can use the following example with 1 Console and 1 Command:
```
  RunScript {
    Console = "prune stats yes"
    Command = "systemctl start tralala"
    RunsWhen = After
  }
```
The resulting show form look like:
```
  RunScript {
    Console = "update stats days=3"
    RunsWhen = "after"
  }
  RunScript {
    Command = "systemctl start tralala"
    RunsWhen = "after"
  }
````
Here we can eventually deduce that console will never be run on client. 
But the last command is again undetermined and operator can't have an idea, without opening the text configuration file to see that the block is written in condensed form and maybe will not be executed on client.

2022-08-10 09:25 UTC, joergsteffens commented
> The resulting show form look like:
> 
> ```
>   RunScript {
>     Console = "update stats days=3"
>     RunsWhen = "after"
>   }
>   RunScript {
>     Command = "systemctl start tralala"
>     RunsWhen = "after"
>   }
> ```
> 
> Here we can eventually deduce that console will never be run on client. But the last command is again undetermined and operator can't have an idea, without opening the text configuration file to see that the block is written in condensed form and maybe will not be executed on client.

I even expect, that `systemctl start tralala` will be executed on the client, as the default of `RunOnClient` is yes.
Anyway, not printing the default value is the default behavior for all directives. It will be not consistent to only change this for the `RunOnClient` directive.
To let the show command also display the default value, there is the `show verbose` command. However, this is currently not working for Runscript sections. If you think, this is required, I can add that.

2022-08-10 09:43 UTC, bruno-at-bareos commented
My concern is that for the moment any console or command if the RunOnClient = No is not specified are run on client and show verbose doesn't confirm that.

so yes we need to fix this. and maybe also fixing console to never be run on client (or there's a use case, that I'm not aware of?)

```
10-Aug 09:38 localhost-fd JobId 1: shell command: run ClientAfterJob "prune stats yes"
10-Aug 09:38 localhost-fd JobId 1: Error: Runscript: ClientAfterJob returned non-zero status=208. ERR=No such file or directory
```
loging use `shell command` also for console command :-(

2022-08-11 07:32 UTC, bruno-at-bareos requested changes
Nice approach, I believe we cover all the case. There's just minor modification to still be included.

2022-08-11 08:44 UTC, joergsteffens commented on systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/backup-bareos-fd-runscript-console-client.conf.in
> +  Description = "Run a console runscripts on the server and a script commands on the client"
I updated the description with another commit.

2022-08-11 08:45 UTC, joergsteffens commented
Now, it warns only once the misconfigured Runscript resource.

2022-08-11 08:59 UTC, bruno-at-bareos commented
I just still have check-sources complaining about 
```
diff --git i/core/src/dird/dird_conf.cc w/core/src/dird/dird_conf.cc
index c13613c86..fb5cdfdb7 100644
--- i/core/src/dird/dird_conf.cc
+++ w/core/src/dird/dird_conf.cc
@@ -1060,9 +1060,7 @@ static void PropagateResource(ResourceItem* items,
               *new_list = new alist<const char*>(10, owned_by_alist);
             }

-            foreach_alist (str, orig_list) {
-              (*new_list)->append(strdup(str));
-            }
+            foreach_alist (str, orig_list) { (*new_list)->append(strdup(str)); }

             SetBit(i, dest->item_present_);
             SetBit(i, dest->inherit_content_);
@@ -1084,9 +1082,7 @@ static void PropagateResource(ResourceItem* items,
               *new_list = new alist<BareosResource*>(10, not_owned_by_alist);
             }

-            foreach_alist (res, orig_list) {
-              (*new_list)->append(res);
-            }
+            foreach_alist (res, orig_list) { (*new_list)->append(res); }

             SetBit(i, dest->item_present_);
             SetBit(i, dest->inherit_content_);
@@ -1110,9 +1106,7 @@ static void PropagateResource(ResourceItem* items,
               *new_list = new alist<const char*>(10, owned_by_alist);
             }

-            foreach_alist (str, orig_list) {
-              (*new_list)->append(strdup(str));
-            }
+            foreach_alist (str, orig_list) { (*new_list)->append(strdup(str)); }

             SetBit(i, dest->item_present_);
             SetBit(i, dest->inherit_content_);
@@ -2476,9 +2470,7 @@ static bool PopulateJobdefaults()
   bool retval = true;

   // Propagate the content of a JobDefs to another.
-  foreach_res (jobdefs, R_JOBDEFS) {
-    PropagateJobdefs(R_JOBDEFS, jobdefs);
-  }
+  foreach_res (jobdefs, R_JOBDEFS) { PropagateJobdefs(R_JOBDEFS, jobdefs); }

   // Propagate the content of the JobDefs to the actual Job.
   foreach_res (job, R_JOB) {
diff --git i/systemtests/tests/python-bareos/test_runscript.py w/systemtests/tests/python-bareos/test_runscript.py
index ccb226d15..2841cc41e 100644
--- i/systemtests/tests/python-bareos/test_runscript.py
+++ w/systemtests/tests/python-bareos/test_runscript.py
@@ -372,7 +372,7 @@ class PythonBareosJsonRunScriptTest(bareos_unittest.Json):
         # },

         jobId = self.run_job(director_root, jobname, level)
-        self.wait_job(director_root, jobId, expected_status=u"Error")
+        self.wait_job(director_root, jobId, expected_status="Error")
         self.search_joblog(director_root, jobId, expected_logs)

     def test_admin_runscript_client(self):
```

2022-08-11 13:20 UTC, bruno-at-bareos commented
In my last manual testing I found that we emit a warning about console command without a RunOnClient=No.
As we change the behaviour (Console command will be always run on Dir) maybe we can disable this warning.
Here the configuration example to trigger the warning

```
  # Only Console command, no warning should be emitted
  RunScript {
    Console = "prune stats yes"
    Console = "update stats days=3"
    Console = ".bvfs_update"
    RunsWhen = After
  }
```

There are configuration warnings:
 * RunScripts with Console commands are not intended to run on clients. Setting 'RunOnClients' to 'no'. Please adapt the RunScript resource in config file /usr/local/etc/bareos/bareos-dir.d/job/BackupCatalog.conf ending in line 24.

```
  # Mixed command then the warning should be shown.
  RunScript {
    Console = "prune stats yes"
    Console = "update stats days=3"
    Command = "systemctl stop mysql"
    RunsWhen = After
  }
```

What's your opinion on this ?

2022-08-11 14:00 UTC, joergsteffens commented
I intentionally added the warning, as the behavior is somehow changed now.
Before you could configure 

```
RunScript {
    Console = "prune stats yes"
    RunsWhen = After
}
```
but as Bareos then tries to execute "prune stats yes" on the client as a shell script (this might work for some commands, that also exists in the OS or if you create `/usr/local/bin/prune`).
You had to configure it as
```
RunScript {
    Console = "prune stats yes"
    RunsWhen = After
    RunsOnClient = No
}
```
And this is still true, just that specifying a Console runscript implicietly sets `RunsOnClient = No` (even if you explicitly set it to Yes !).
This is not behavior we like to have, therefore we issue the Warning, so that the Administrator sets it to the correct value.

2022-08-11 19:54 UTC, bruno-at-bareos approved these changes
Nice revision and work. all the tests done look really great now.
I just let a comment about a "inherit" replacement if you want to fix it.

Otherwise if build and tests are green, can be merged.

2022-08-11 19:54 UTC, bruno-at-bareos commented on core/src/dird/dird_conf.cc
> +      PrintConfigRunscript(send, item, inherited, verbose);
Shouldn't be? 
```suggestion
      PrintConfigRunscript(send, item, print_as_comment, verbose);
```

2022-08-11 20:06 UTC, joergsteffens commented on systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/backup-bareos-fd-runscript-console-client.conf.in
> +  Description = "Run console runscripts on the Director and a script command on the client"
What do you mean by "fail check"? This jobs will be executed without problems (console commands on the Director and the external command on the client).

2022-08-12 05:35 UTC, bruno-at-bareos commented on systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/backup-bareos-fd-runscript-console-client.conf.in
> +  Description = "Run console runscripts on the Director and a script command on the client"
Tested afterward. yes work like described.

2022-08-12 06:12 UTC, merged