config: add FS Type = vfat in LinuxAll.conf for UEFI partition.
bareos/bareos pull request #1236
Opened 2022-08-23 15:03 UTC by bruno-at-bareos

This PR add FS Type = vfat to LinuxAll.conf so complete linux with UEFI partition will be backup and can be restored.
Small improvements done into doc Director.rst

### Thank you for contributing to the Bareos Project!

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted
- [ ] If backport: add original PR number and target branch at top of this file: **Backport of PR#000 to bareos-2x**

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-08-25 14:40 UTC, pstorz requested changes
Only the quotes around the directive in the changelog, nothing else.

Good work!

2022-08-25 14:40 UTC, pstorz commented on CHANGELOG.md
> +- dird: Added FS Type = vfat in LinuxAll.conf for UEFI partition [PR #1236]
```suggestion
- dird: Added `FS Type = vfat` in LinuxAll.conf for UEFI partition [PR #1236]
```

2022-08-25 15:19 UTC, bruno-at-bareos commented on CHANGELOG.md
> +- dird: Added FS Type = vfat in LinuxAll.conf for UEFI partition [PR #1236]
will fix that in amend mode then.

2022-08-29 10:13 UTC, pstorz approved these changes
Good work!

2022-08-29 11:12 UTC, merged