docs: Document howto upgrade from generic python plugin
bareos/bareos pull request #1260
Opened 2022-09-15 14:22 UTC by bruno-at-bareos

This PR add instructions to Update Bareos chapter about python plugin `broken packages` with `apt upgrade`

[OP #5250] [OP #5155]
#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Separate commit for CHANGELOG.md ("update CHANGELOG.md"). The PR number is correct.

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-09-23 15:07 UTC, joergsteffens requested changes
I've tested with bareos-19.2 and packages `bareos-filedaemon` and `bareos-filedaemon-python-plugin`(and the automatic dependency `bareos-common`).

While `apt upgrade bareos-filedaemon` fails, you can work around it by:

`apt install bareos-filedaemon`

or 

`apt full-upgrade bareos-filedaemon`

will both succeed, but remove the package `bareos-filedaemon-python-plugin`.
However, if you specify 

`apt full-upgrade bareos-filedaemon bareos-filedaemon-python3-plugin`

or even only 

`apt full-upgrade bareos-filedaemon-python3-plugin`

or

`apt install bareos-filedaemon bareos-filedaemon-python3-plugin`

or

`apt install bareos-filedaemon-python3-plugin`

will all succeed and achieve what is requested.
Of course, same is true if you replace `bareos-filedaemon-python3-plugin` by `bareos-filedaemon-python2-plugin`

Given this, I'm not sure it is worth to spend a section in the Update chapter for it, as it only affects old versions. But I understood, that there have been questions about this. Would  placing the section into https://docs.bareos.org/Appendix/FAQ.html instead be helpful?

2022-09-26 14:46 UTC, bruno-at-bareos commented
Hi @joergsteffens thanks a lot for your precious addition and tests.
I really like the 

```apt full-upgrade bareos-filedaemon bareos-filedaemon-python3-plugin``` trick and I agree that should do something with this and will more update the FAQ than the upgrade.

2022-09-26 17:14 UTC, joergsteffens requested changes
Looks good. I've added a few minor comments.

2022-09-26 17:14 UTC, joergsteffens commented on docs/manuals/source/Appendix/FAQ.rst
> +In this case, it is advised to use `full-upgrade` option of apt and directly move to new recommended python3 plugin.
```suggestion
In this case, it is advised to use :command:`apt` with `full-upgrade` and directly move to new recommended python3 plugin.
```

2022-09-26 17:14 UTC, joergsteffens commented on docs/manuals/source/Appendix/FAQ.rst
> +
```suggestion

.. index::
   single: Platform; Debian
   single: bareos-19.2; Upgrade with Python packages on Debian
```

2022-09-26 17:14 UTC, joergsteffens commented on docs/manuals/source/Appendix/FAQ.rst
> +   apt upgrade bareos bareos-bconsole bareos-client bareos-common bareos-database-common bareos-database-postgresql bareos-database-tools bareos-director bareos-filedaemon bareos-storage bareos-stora
```suggestion
   apt upgrade bareos bareos-director bareos-filedaemon
```

2022-09-27 07:41 UTC, bruno-at-bareos commented
All changes applied, once agreed I will squash I propose to add the CHANGELOG

2022-09-27 12:23 UTC, joergsteffens approved these changes
Very well.

2022-09-27 12:39 UTC, joergsteffens approved these changes

2022-09-27 12:39 UTC, merged