improve portability
bareos/bareos pull request #1270
Opened 2022-09-30 07:55 UTC by joergsteffens

While trying to compile and test (ctest) Bareos on ARM (using qemu), I had to do 2 small changes to make it work.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Separate commit for CHANGELOG.md ("update CHANGELOG.md"). The PR number is correct.

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-10-19 11:36 UTC, pstorz requested changes
Better use static_cast instead of c casts, see https://google.github.io/styleguide/cppguide.html#Casting

2022-10-19 11:36 UTC, pstorz commented on core/src/droplet/libdroplet/src/backend/posix/backend.c
> +  snprintf(buf, sizeof(buf), "%lu", (unsigned long)st.st_nlink);
```suggestion
  snprintf(buf, sizeof(buf), "%lu", static_cast<unsigned long>(st.st_nlink));
```

2022-10-19 11:36 UTC, pstorz commented on core/src/droplet/libdroplet/src/backend/posix/backend.c
> +  snprintf(buf, sizeof(buf), "%ld", (long int)st.st_blksize);
```suggestion
  snprintf(buf, sizeof(buf), "%ld", static_cast<long int>(st.st_blksize));
```

2022-10-20 12:08 UTC, joergsteffens commented
Applied suggestions, appiled bareos-check-sources, rebased and force-pushed (because it is a trivial PR).

2022-10-24 07:43 UTC, merged