dird: fix `show directors` not working as expected
bareos/bareos pull request #1315
Opened 2022-11-15 14:09 UTC by alaaeddineelamri

### Thank you for contributing to the Bareos Project!

#### Description

`show directors` command does not work as expected due to a previous update to enums.
This PR fixes the issue.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Separate commit for CHANGELOG.md ("update CHANGELOG.md"). The PR number is correct.

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-11-28 16:42 UTC, joergsteffens requested changes
Testing shows, that the bconsole show command works as expected.
However, there are (now?) discrepancies between the bconsole show command and the --export-config command line argument:

### bconsole:
```
*show DONTEXIST
Resource DONTEXIST not found

*show job=DONTEXIST
job resource DONTEXIST not found.
```
Okay.

### cmdline:

```
sbin/bareos_dir-python-bareos  -c etc/bareos --xc job DONTEXIST
No ***UNKNOWN*** resource defined

$ sbin/bareos_dir-python-bareos  -c etc/bareos --xc director
<no outputp>

$ sbin/bareos_dir-python-bareos  -c etc/bareos --xc DONTEXIST
<no outputp>
```

`--xc director` doesn't work. Missing error output.

### Other differences:
* bconsole:
  * show job => show jobdefs
  * show jobs => show jobs
* cmd:
  * `--xc job => show jobs`
  * `--xc jobs => <empty>`

The job and jobs keywords are handled differently.

2022-11-28 16:42 UTC, joergsteffens commented on core/src/dird/ua_output.cc
> +      case -1:
Can you define these magic numbers somewhere?

2022-11-28 16:43 UTC, joergsteffens commented
Please also run `bareos-check-sources` and maybe you can find a  better usable title to also be addable to the CHANGELOG file.

2022-11-29 15:23 UTC, alaaeddineelamri commented
The differences between show and export config were already there on master, so the changes here did not add anything new to that.

The issue with
```
$ sbin/bareos_dir-python-bareos  -c etc/bareos --xc director
<no outputp>
```
is the same thing in relation to the enum changes, but not directly involved with the show command. I pushed a fix for that too.

The show command and the export config option do not use exactly the same code. In case we want them to behave the same, I can implement changes for that. Otherwise, if we want to keep this PR uniquely for the purpose of fixing the director config not showing up, we can do the unification of behavior in another PR.

2022-11-30 10:12 UTC, joergsteffens approved these changes

2022-11-30 11:27 UTC, merged