fix: possible fix for crash on dir
bareos/bareos pull request #1327
Opened 2022-12-02 14:22 UTC by alaaeddineelamri

### Thank you for contributing to the Bareos Project!

#### Description

This PR fixes a crash that occurs on rescheduling jobs.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Separate commit for CHANGELOG.md ("update CHANGELOG.md"). The PR number is correct.

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2022-12-06 09:59 UTC, sduehr commented
This occured with the following config:
```
  Reschedule On Error = yes
  Reschedule Interval = 30 minutes
  Reschedule Times = 7
  Max Wait Time = 5 minutes
```
and it occured when the job was started at the rescheduled start time.

So the description should be:
This PR fixes a crash that occurs on starting rescheduled jobs.

2022-12-09 07:29 UTC, pstorz requested changes
See comment, `set -e` is missing in testrunner-reschedule

2022-12-09 07:29 UTC, pstorz commented on systemtests/tests/scheduler/testrunner-reschedule
> +set -o pipefail
```suggestion
set -e
set -o pipefail
```

2022-12-09 14:49 UTC, pstorz approved these changes
Good work!

2022-12-09 14:49 UTC, merged