dird: cats: adapt `purge`command to delete jobs with specific jobstatus and/or from specific pool
bareos/bareos pull request #1349
Opened 2023-01-04 12:26 UTC by alaaeddineelamri

### Thank you for contributing to the Bareos Project!

#### Description

This PR adds the ability for the `purge` to delete jobs with specific a jobstatus and/or from specific pool.
The command used to only do so for specific volumes or clients.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Separate commit for CHANGELOG.md ("update CHANGELOG.md"). The PR number is correct.

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-01-20 19:14 UTC, joergsteffens requested changes

2023-01-20 19:14 UTC, joergsteffens commented on core/src/dird/ua_purge.cc
> +
PurgeJobsFromClient asks for confirmation before purging. Shouldn'd PurgeJobsFromPool do the same? (PurgeJobsFromVolume also does not ask).

2023-01-20 19:14 UTC, joergsteffens commented on core/src/dird/ua_purge.cc
> +
When  purging all jobs from a volume, the volume is still marked as full. When purging the last job from a volume, the volume will be marked as purged afterwards.

2023-01-20 19:17 UTC, joergsteffens commented
I also did some modifications directly in commits. Unfortunately, I'd not have the permission to modify this PR directly (I though, did is the default?). Instead I pushed my suggestions to https://github.com/joergsteffens/bareos/tree/dev/joergs/master/s5201-purge-failed-jobs

2023-02-21 12:34 UTC, alaaeddineelamri commented on core/src/dird/ua_purge.cc
> +  bool purged = false;
it's still used just underneath

2023-03-16 13:05 UTC, joergsteffens requested changes
Nearly done, but pr-tool complains:
```
 ✗  Commit checks failed:
	f874336d4 refactor: systemtest: updated systemtest: body contains line longer 72 chars
	aa771a59e refactor: ua_purge.cc: remove bailouts, rename and reorder variables: headline too long
 ✗  bareos-check-sources --since=421f8eb125967d7faac63cf9acf0eddff16d2244 reported:
	Plugin 'compress c block comments' would modify 'core/src/cats/sql.cc'
	Plugin 'fix copyright year' would modify 'core/src/cats/sql.cc'
	Plugin 'fix copyright year' would modify 'core/src/cats/sql.h'
```

2023-03-16 13:05 UTC, joergsteffens commented on systemtests/tests/pruning/testrunner
> +purge jobs client jobstatus=E yes
```suggestion
purge jobs client=bareos-fd jobstatus=E yes
```
Cosmetical change, but without I've been confused at first (if only only client is configured, it gets autoselected).

2023-03-23 11:49 UTC, joergsteffens approved these changes

2023-03-24 11:39 UTC, merged