Fix crash on volume swap
bareos/bareos pull request #1356
Opened 2023-01-17 07:18 UTC by arogge

Fix a problem introduced in Bareos 22 with PR #1271 where the SD would crash on a volume swap.

This PR also introduces a testing backend to make it easier to test autochangers. However, a change in the Device interface is required for this (so we shouldn't backport that).

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General
- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Separate commit for CHANGELOG.md ("update CHANGELOG.md"). The PR number is correct.

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems

##### Tests

- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-01-18 16:19 UTC, pstorz requested changes
Good work! Impressive, how simple now it is to add a new backend device.

2023-01-18 16:19 UTC, pstorz commented on core/src/stored/vol_mgr.cc
> +          dcr->SetDev(dev);                     /* restore dev */
```suggestion
          auto original_dcr_dev = dcr->dev;
          dcr->SetDev(vol->dev);                /* temp point to other dev */
          slot = GetAutochangerLoadedSlot(dcr); /* get slot on other drive */
          dcr->SetDev(original_dcr_dev);                     /* restore dev */
```

2023-01-18 16:56 UTC, arogge commented on core/src/stored/backends/CMakeLists.txt
> +    TARGET bareossd-autochanger_test PROPERTY POSITION_INDEPENDENT_CODE ON
I guess we can remove it in this case.
Basically, as we have it enabled in other parts of the code and it is the default for SHARED and MODULE targets, we only have to set it on some special occassions.

If you build without dynamically loadable backends, these will be linked statically into the libbareossd shared library. Therefore the backends needs to have PIC enabled.

Maybe we could globabally enable `CMAKE_POSITION_INDEPENDENT_CODE` in `core/CMakeLists.txt` so it is the default.

2023-01-18 16:57 UTC, arogge commented on core/src/stored/vol_mgr.cc
> +          dcr->SetDev(dev);                     /* restore dev */
Good idea. I'll rename it.

2023-01-19 15:12 UTC, pstorz approved these changes
Good work!

2023-01-25 15:16 UTC, merged