doc: use python3 in Plugin Name sample
bareos/bareos pull request #1401
Opened 2023-03-07 12:44 UTC by bruno-at-bareos

After report in ML, Mantis, and support cases:
This PR propose to change `Plugin Names = "python"` samples to `Plugin Names = "python3"` in documentation, making it clear to everyone that parameter need to be adjusted depending on the python version you use.

It is proposed to also backport this to branch-22

OP#5425

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-03-22 20:13 UTC, sduehr commented on docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
> +   :caption: Debin,Ubuntu enabling php8-fpm support on Apache2 example
```suggestion
   :caption: Debian, Ubuntu enabling php8-fpm support on Apache2 example
```

2023-03-23 09:17 UTC, bruno-at-bareos commented
> Thanks, only few changes requested, and could you please also change to Plugin Names = python3 in VMwarePlugin.rst.inc?

Done in last push (forced then) added to first commit.

2023-03-23 11:27 UTC, sduehr approved these changes
Thanks, looks good now.

2023-03-28 09:54 UTC, bruno-at-bareos commented
We just add the fact that we want to add also the PackageHub needs for SL12SP5

2023-03-28 15:10 UTC, sduehr requested changes
Thanks, only found a typo.

2023-03-28 15:10 UTC, sduehr commented on docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
> +-  On SUSE Linux Enterprise 12 you need the additional SUSE Linux Enterprise Module for Web Scripting 12 and additionnal repository :strong:`Package Hub` to satisfy apache2-mod-fcgid requirement.
```suggestion
-  On SUSE Linux Enterprise 12 you need the additional SUSE Linux Enterprise Module for Web Scripting 12 and additional repository :strong:`Package Hub` to satisfy apache2-mod-fcgid requirement.
```

2023-03-29 07:19 UTC, bruno-at-bareos commented on docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
> +-  On SUSE Linux Enterprise 12 you need the additional SUSE Linux Enterprise Module for Web Scripting 12 and additionnal repository :strong:`Package Hub` to satisfy apache2-mod-fcgid requirement.
Fixed. sorry.

2023-03-30 13:03 UTC, sduehr approved these changes
Thanks, looks good.

2023-03-30 13:09 UTC, merged