Fix problem with reoccuring files in always incremental
bareos/bareos pull request #1416
Opened 2023-03-21 09:55 UTC by arogge

**Backport of PR #13950 to bareos-22** (remove this line, if it no backport)

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-03-21 12:15 UTC, pstorz requested changes
See comments.

2023-03-21 12:15 UTC, pstorz commented on systemtests/tests/virtualfull-deletedfiles/testrunner-05-consolidate
> +if ! grep -q 'Consolidating JobIds .* containing 2 files' "$tmp/$myname.log"; then
`expect_grep` again :)

2023-03-21 12:15 UTC, pstorz commented on systemtests/tests/virtualfull-deletedfiles/testrunner-05-consolidate
> +quit
```suggestion
sqlquery                                                                           
select count(*) from file where jobid=5;
quit                                      
```

2023-03-21 12:15 UTC, pstorz commented on systemtests/tests/virtualfull-deletedfiles/testrunner-05-consolidate
> +
```suggestion
expect_grep '^| *4 |' "$tmp/$myname.log" "Number of files including fileindex 0 mismatch"
```

2023-03-21 12:15 UTC, pstorz commented on systemtests/tests/virtualfull-deletedfiles/testrunner-05-consolidate
> +
This is to make sure that the two deleted files really where replicated.

2023-03-22 07:43 UTC, sebsura commented on systemtests/tests/reload/CMakeLists.txt
> -
yes. we fixed that issue.  In fact only add-second-director was broken anyways.

2023-03-22 09:29 UTC, arogge commented on core/src/dird/vbackup.cc
> +    }
as discussed yesterday that's not really possible to do.

2023-03-23 14:25 UTC, merged