scripts: config-lib improve setup_sd_user
bareos/bareos pull request #1448
Opened 2023-04-17 10:04 UTC by bruno-at-bareos

With the current code, usermod -G .... call is done quoted generating a warning on several distribution when installing bareos-storage package. 
```
Running scriptlet: bareos-storage-22.0.4~pre51.ab585a79e-44.el8.x86_64                                                                                                                                                  19/39
/usr/lib/bareos/scripts/bareos-config-lib.sh: line 370: usermod -G bareos,tape,disk: command not found
Warning: failed: usermod -G bareos,tape,disk bareos
```

This PR propose to use simpler command construction by calling usermod -a -G group,group in all case.
usermod doesn't failed if the user already belong to the group, and with -a we preserve the already defined group.

- Use flag -a with -G on usermod command.
- Remove unneeded code for additional groups.

OP#5450

I propose to also create a backport to 22 for that one.

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-06-01 12:59 UTC, arogge requested changes
I'm really sorry I'm bothering you every time. But you really have a talent for picking the worst shell script that has the most potential for improvement...

2023-06-12 10:39 UTC, arogge commented
This looks great! I'll try it and discuss with @pstorz if we should delay 22.1.0 to include this.

2023-06-12 11:23 UTC, bruno-at-bareos commented on core/scripts/bareos-config-lib.sh.in
> -            # Build a list of all groups the user is already in.
I'm not against reviewing and modifying more deeply this code. Here I want to fix as quickly and as simply as possible a bug introduced in 22.0

I'm pretty sure we can get ride of any of those functions called only by the packaging scripts and do a proper rewrite only in packaging for 23?

setup_sd_user is used in `core/platforms/packaging/bareos.spec:1781` and `debian/bareos-storage.postinst.in`

2023-06-12 11:55 UTC, arogge approved these changes

2023-06-12 12:40 UTC, merged