docs: replace GZIP compression by LZ4 and MD5/SHA1 signature by XXH128
bareos/bareos pull request #1453
Opened 2023-04-24 13:28 UTC by bruno-at-bareos

This PR propose to update our documentation by replacing the slowest compression algorithm we have (GZIP) by a modern and well supported format LZ4.
We also replaced the oldest MD5 or SHA1 signature exemple by the XXH128

OP#5451
#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-04-24 14:18 UTC, joergsteffens requested changes

2023-04-24 14:18 UTC, joergsteffens commented on docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
> +    ingle: Volume; Management; Key Concepts and Resource Records
```suggestion
   single: Volume; Management; Key Concepts and Resource Records
```

2023-04-24 14:18 UTC, joergsteffens commented on docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
> +    single: Pool; Options to Limit the Volume Usage>`\
```suggestion
   single: Pool; Options to Limit the Volume Usage>`\
```

2023-04-24 14:37 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
> +    ingle: Volume; Management; Key Concepts and Resource Records
tx applied

2023-04-24 14:38 UTC, bruno-at-bareos commented on docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
> +    single: Pool; Options to Limit the Volume Usage>`\
ty applied also fixing end of line ;-)

2023-05-04 12:30 UTC, joergsteffens approved these changes

2023-05-04 12:31 UTC, merged