fix support for non-tape blockdevices
bareos/bareos pull request #1554
Opened 2023-09-14 08:06 UTC by sebsura

### Thank you for contributing to the Bareos Project!

Currently bareos does some things differently if the target device is a tape.  But in some of those cases it should consider all block based devices instead.

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-09-21 13:57 UTC, arogge requested changes
As discussed I would love to have the network_order replaced with the super-naive implementation I made up.

2023-10-03 08:25 UTC, bruno-at-bareos commented
I'm proposing to add also the following patch to fix OP#5563 

```diff
diff --git i/core/src/stored/butil.cc w/core/src/stored/butil.cc
index b71fca85c..ec5488439 100644
--- i/core/src/stored/butil.cc
+++ w/core/src/stored/butil.cc
@@ -145,7 +145,7 @@ static bool setup_to_access_device(DeviceControlRecord* dcr,
   if (!VolumeName.empty()) {
     bstrncpy(VolName, VolumeName.c_str(), sizeof(VolName));
     if (VolumeName.size() >= MAX_NAME_LENGTH) {
-      Jmsg0(jcr, M_ERROR, 0,
+      Jmsg0(jcr, M_FATAL, 0,
             _("Volume name or names is too long. Please use a .bsr file.\n"));
     }
   } else {
```

Comment is :
- exit with M_FATAL instead M_ERROR in case volume name(s) are too long

2023-10-04 12:46 UTC, sebsura commented on core/src/lib/network_order.h
> +  network() noexcept : network{T{}} {}
yep!

2023-10-04 12:47 UTC, sebsura commented on core/src/lib/network_order.h
> +  constexpr network(const T& value) noexcept
I think implicit conversions are fine here. I added the implicit hint.

2023-10-04 12:47 UTC, sebsura commented on core/src/lib/edit.h
> +#define DEFAULT_FORMAT_LENGTH 27
yep!

2023-10-10 13:57 UTC, arogge approved these changes

2023-10-18 09:52 UTC, merged