rename gettext macro
bareos/bareos pull request #1588
Opened 2023-11-06 11:14 UTC by arogge

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-11-07 07:58 UTC, sebsura requested changes
Looks good.  I added some suggestions, tell me what you think of them.

2023-11-07 07:58 UTC, sebsura commented on core/src/dird/ua_update.cc
> +        AddPrompt(ua, T_("Done"));                   /* 18 */
```suggestion
    AddPrompt(ua, T_("Enabled"));                    /* 14 */
    AddPrompt(ua, T_("RecyclePool"));                /* 15 */
    AddPrompt(ua, T_("Action On Purge"));            /* 16 */
    AddPrompt(ua, T_("Storage"));                    /* 17 */
    AddPrompt(ua, T_("Done"));                       /* 18 */
```
Klappt zwar auch so wie es war, sieht aber komisch aus.

2023-11-07 07:58 UTC, sebsura commented on core/src/lib/ini.cc
>      //
delete if not needed

2023-11-07 07:58 UTC, sebsura commented on core/src/include/baconfig.h
> +#  define N_(s) (s)
What is the difference between `N_()` and `NT_()` ? Should we unify those to just `NT_()` ?

2023-11-07 07:58 UTC, sebsura commented on core/src/lib/ini.cc
>      //
Same

2023-11-07 07:58 UTC, sebsura commented on core/src/lib/tls_openssl.cc
> +  std::string message{T_("TLS shutdown failure.")};
```suggestion
  const char* message = T_("TLS shutdown failure.");
```
This does not need to be changed, but feel free to do so.

2023-11-07 07:58 UTC, sebsura commented on core/src/lib/var.cc
> +    T_("octal value too large"),        /* VAR_ERR_OCTAL_TOO_LARGE */
For arrays such as this I much prefer the C syntax:
```suggestion
    [VAR_OK] = T_("everything ok"),
    [VAR_ERR_INCOMPLETE_NAMED_CHARACTER] = T_("incomplete named character"),
    [VAR_ERR_INCOMPLETE_HEX] = T_("incomplete hexadecimal value"),
    [VAR_ERR_INVALID_HEX] = T_("invalid hexadecimal value"),
    [VAR_ERR_OCTAL_TOO_LARGE] = T_("octal value too large"),
```
even if not c++ standard compliant.  But this change does not belong in this pr.

2023-11-07 16:18 UTC, arogge commented
I had to rebase and force-push to fix some conflicts. Sorry for that.

2023-11-09 13:46 UTC, sebsura requested changes
You cannot remove `ini.h` and `ini.cc` since they are actually required by `test-plugin-fd.cc`.

If that file is not used anymore, we should probably delete it as well.

2023-11-16 09:16 UTC, arogge commented
That test plugin looks like something that bitrotted away. At least there is no build configuration on Jenkins that would even try to build it.
I'll see if we should re-enable or remove it.

2023-11-17 10:35 UTC, sebsura approved these changes
Good work!  You just need to fix the build issues but Ill already approve of it for now.

2023-11-17 14:35 UTC, merged