autoxflate: fix autoxflate on replication
bareos/bareos pull request #1594
Opened 2023-11-10 10:58 UTC by sebsura

### Thank you for contributing to the Bareos Project!

**Backport of PR #1576 to bareos-22**

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-11-16 16:07 UTC, pstorz requested changes
Looks good, please see comments

2023-11-16 16:07 UTC, pstorz commented on systemtests/tests/autoxflate/CMakeLists.txt
> +#   Copyright (C) 2021-2023 Bareos GmbH & Co. KG
```suggestion
#   Copyright (C) 2023-2023 Bareos GmbH & Co. KG
```

2023-11-16 16:07 UTC, pstorz commented on core/src/stored/device_resource.cc
> +           "also has to be set.\n"),
```suggestion
         _("Device %s: 'AutoDeflate' is set but required 'AutoDeflateAlgorithm' is missing.\n"),
```

2023-11-17 10:27 UTC, sebsura commented on core/src/stored/device_resource.cc
> +           "also has to be set.\n"),
changed

2023-11-17 11:22 UTC, pstorz approved these changes

2023-11-17 11:54 UTC, merged