Dev/bruno/master/plugin postgresql parameter from cluster
bareos/bareos pull request #1599
Opened 2023-11-15 16:35 UTC by bruno-at-bareos

With previous version of the code, the plugin in restore may overwrite real data if the given data dir root was a symlink.
This new version will connect to the cluster and  will ask directly its configuration parameters.

- remove no more used parameter `postgresql_data_dir`
- `wal_archive_dir` parameter is checked if it is a symlink, if the case the real location is retrieved and backup instead of the symlink, a warning is added to the joblog
- backup external configuration: on debian with the use to pg_*cluster* tools configuration is not stored in the data directory. the plugin now try its best to backup the directory content where postgresql.conf reside (/etc/postgesql/<version>/<instance>/)
- add a systemtest to test debian/ubuntu specific location and tools.

### TODO
- [] revisit the documentation
- [] stash and reorder commits
- [] rework functions ordering

Fix Issue [#1563](https://bugs.bareos.org/view.php?id=1563)
OP#5610

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-11-16 18:04 UTC, pstorz requested changes
See comments. Good work!

2023-11-16 18:04 UTC, pstorz commented on docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PostgreSQLPlugin.rst.inc
> +- the Bareos FD Python plugins work in general, try one of the shipped simple sample plugins
```suggestion
- the Bareos FD Python plugins works in general, try one of the shipped simple sample plugins
```

2023-11-16 19:17 UTC, bruno-at-bareos commented on core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
> +    def __get_cluster_configuration_parameters(self):
Yes it is in db_user (light sentence) and detailed in troubleshooting

2023-11-20 10:39 UTC, pstorz approved these changes

2023-11-20 11:12 UTC, merged