dird: remove optimize_for_size/optimize_for_speed
bareos/bareos pull request #1612
Opened 2023-12-05 12:18 UTC by sebsura

### Thank you for contributing to the Bareos Project!

This PR removes the `optimize_for_*` options from the director.  It also fixes a memory leak.
It also includes a fix for a memory leak inside the director.

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2023-12-05 12:37 UTC, pstorz requested changes
Looks good! Only one typo in the comment.
Backport needs only to deprecate the directives.
Good work!

2023-12-05 12:37 UTC, pstorz commented on core/src/dird/ua_restore.cc
> +   * to ensure that we free the tree here before returning false; otherwies
```suggestion
   * to ensure that we free the tree here before returning false; otherwise
```

2023-12-05 12:40 UTC, sebsura commented on core/src/dird/ua_restore.cc
> +   * to ensure that we free the tree here before returning false; otherwies
fixed

2023-12-05 12:43 UTC, pstorz approved these changes
Good work!

2023-12-07 17:14 UTC, pstorz requested changes
Looks good, but why do we have so many empty files?(.rst.inc).
I guess we can leave them away?

2023-12-11 08:05 UTC, pstorz approved these changes

2023-12-12 08:57 UTC, merged