chore: add build patch for `sprintf` in macos builds
bareos/bareos pull request #1636
Opened 2023-12-17 05:29 UTC by chenrui333

```
/tmp/bareos-client-20231217-15168-qlx505/bareos-Release-23.0.0/core/src/tests/job_control_record.cc:62:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    sprintf(jobs[i]->Job, "%d-test", 123 + i);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/tmp/bareos-client-20231217-15168-qlx505/bareos-Release-23.0.0/core/src/tests/job_control_record.cc:121:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
  sprintf(jcr->Job, "987-654-321");
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
```

### Thank you for contributing to the Bareos Project!

**Backport of PR #0000 to bareos-2x** (remove this line if this is no backport; for backport use cherry-pick -x)

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

---

relates to https://github.com/Homebrew/homebrew-core/pull/157558

2023-12-21 12:46 UTC, sebsura requested changes
Thanks for your contribution. The changes are great.  Please add yourself to the AUTHORS file, so we that this can be merged.

2023-12-21 12:49 UTC, sebsura commented
```
✗  Commit checks failed:
  bac6e7f30 chore: add build patch for `sprintf` in macos builds: body contains line longer 72 chars
✗  bareos-check-sources --since=1bbd14cf1d9c05071559fd3a98bd2e5dd6da6e9a reported:
  Plugin 'fix copyright year' would modify 'core/src/tests/job_control_record.cc'
```
pr-tool also reported these problems.

2024-01-05 06:26 UTC, sebsura commented
I fixed the problems and added you to the authors file.  If you did not want to be added, please leave a comment here!

2024-01-05 13:24 UTC, chenrui333 commented
> I fixed the problems and added you to the authors file. If you did not want to be added, please leave a comment here!

happy to be in the authors list, thanks!

2024-01-08 12:37 UTC, sebsura approved these changes

2024-01-08 12:46 UTC, merged

2024-01-10 16:48 UTC, chenrui333 commented
Thanks @sebsura!