core: sql_* add leading space to sql construct
bareos/bareos pull request #1656
Opened 2024-01-09 14:56 UTC by bruno-at-bareos

This PR aims to:
- fix ERROR: trailing junk after numeric literal at or near "123A" in sql_list.cc
- Add IF EXISTS in DROP TABLE statement
- unifomize the query in sql_upgrade.cc
- control all sql function for missing space

OP#5667

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-01-10 11:43 UTC, sebsura requested changes
Great Job!

2024-01-10 12:21 UTC, bruno-at-bareos commented on core/src/cats/bvfs.cc
>    Mmsg(query, "CREATE TABLE btemp%s AS ", output_table);
I didn't put blindly a space at ALL end of queries, it was more add space when there's a construct with if or a possible extension of the query string.
Query like line 720 will never be extended, nor intended to.

2024-01-11 05:45 UTC, sebsura commented on core/src/cats/bvfs.cc
>    Mmsg(query, "CREATE TABLE btemp%s AS ", output_table);
But the query does get extended (unless im misunderstanding you)

```
722 PmStrcat(query, tmp.c_str());
757 if (init) { query.strcat(" UNION "); }
768 query.strcat(tmp.c_str());
...
```
Technically the space is already inside the `" UNION "` string, but that can easily lead to the problem we have.  Also the query starting at 759 actually does end in a space, so the precedent is set.

2024-01-11 09:00 UTC, sebsura approved these changes
Thanks for your work!

2024-01-11 11:10 UTC, merged