cmake: put generated files into CMAKE_BINARY_DIR
bareos/bareos pull request #1707
Opened 2024-02-06 12:49 UTC by arogge

This PR strives to move as much of the files generated by cmake into the CMAKE_BINARY_DIR instead of putting them into the source tree.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Check backport line
- [x] Required backport PRs have been created
- [x] PR 67 in the CD repository is merged

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

2024-02-08 09:06 UTC, bruno-at-bareos commented
Don't we want to also move the generated part of the webui ?
In .gitignore

2024-02-27 15:27 UTC, pstorz requested changes
Looks good, please resolve conflict.

2024-03-11 10:00 UTC, sebsura commented
I fixed the conflict.

2024-03-11 13:06 UTC, pstorz approved these changes

2024-03-12 07:38 UTC, merged