fix various memory leaks
bareos/bareos pull request #1723
Opened 2024-03-01 10:45 UTC by sebsura

### Thank you for contributing to the Bareos Project!

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-05-17 15:13 UTC, arogge requested changes
That is a huge improvement! How did you find all of these?
I have a few remarks. Nothing critical though.

2024-05-23 12:11 UTC, sebsura commented
I gathered all the logs created by asan with our test suite.

2024-05-23 12:27 UTC, sebsura commented on core/src/dird/dbcheck_utils.cc
> +
Just noticed that they are in fact used by `dbcheck.cc`, just not cleaned up.  I guess we do not have a test that currently tests this code path.  Ill see if I can add one test.

2024-05-24 04:55 UTC, sebsura commented on core/src/stored/acquire.cc
> +    memset(store.get(), 0, sizeof(DirectorStorage));
done

2024-05-24 04:55 UTC, sebsura commented on core/src/stored/acquire.cc
>      store->append = false;
done

2024-05-24 04:55 UTC, sebsura commented on core/src/stored/acquire.cc
> +    rctx.store = store.get();
done

2024-05-24 04:56 UTC, sebsura commented on core/src/dird/dbcheck_utils.h
> +void FreeIdList(s_id_ctx* id_list);
moved it next to the other idlist functions

2024-05-24 14:48 UTC, arogge approved these changes
The code looks great.
However, the new dbcheck test fails everywhere, so you'll have to take another look.

2024-05-24 14:49 UTC, arogge commented
Do you think we should backport some/all of these into 23?

2024-05-27 04:33 UTC, sebsura commented
Ill try to backport it and ill see what works.

2024-05-29 17:23 UTC, merged