fix sql error on bad virtualfull; detect parsing errors with strtod
bareos/bareos pull request #1725
Opened 2024-03-01 12:11 UTC by sebsura

### Thank you for contributing to the Bareos Project!

This pr makes it so prev_jr an optional, so that code can check whether this particular member was initialized or not.
Previously the cleanup did not check whether prev_jr was  initialised before it tried to clean it up (this happened if the
job ended in an error quickly).

It also changes the number parsing code somewhat.   Now we check that everything is parsed, not just that something was parsed.  In particular, with certain locales, we used to parse `1,5` as `1` and did not emit any errors since we managed to parse _something_.
Now we actually check if any characters are left over and fail the parsing if so.

Additionally a small enhancement was added to the parsing routines.  Previously we could parse durations like
`1 Year 5 Days 10 Hours´ correctly, but we could not parse numbers like `1 TB 500 GB`, since the code did not loop until every token was consumed.   This PR unified the duration/number parsing somewhat so that now even numbers can be split like above.

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-03-05 09:33 UTC, sebsura commented on core/src/dird/consolidate.cc
> +        // jcr->dir_impl->previous_jr = JobDbRecord{};
remove

2024-03-28 09:28 UTC, pstorz requested changes
Looks good. I have enabled a former commented out test in test_edit.cc
and it fails. It seems that the last single 1 without modifier ist not accepted.

2024-05-14 07:00 UTC, pstorz requested changes

2024-05-14 14:41 UTC, sebsura commented on core/src/tests/test_edit.cc
>    // work
fixed

2024-05-16 10:39 UTC, pstorz approved these changes

2024-06-05 06:52 UTC, merged