update debian/copyright
bareos/bareos pull request #1753
Opened 2024-03-28 11:31 UTC by joergsteffens

Fix adding webui/copyright, remove unimportant sections, update to 2024.

### Thank you for contributing to the Bareos Project!

**Backport of PR #0000 to bareos-2x** (remove this line if this is no backport; for backport use cherry-pick -x)

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Check backport line
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-04-08 13:07 UTC, bruno-at-bareos requested changes
Nice work.
- There's a fix for ./core/src/win32/plugins/filed/mssqlvdi-fd.cc instead of .c
- A control to see why it would be mandatory to have it included in exception as it is AGPL.
- We need to decide if we want this as LICENSE.txt in github root folder and then use that one for packaging.

2024-04-08 14:41 UTC, joergsteffens commented on debian/copyright.core_exceptions
>  Files: core/src/win32/plugins/filed/mssqlvdi-fd.c
fixed.
Another name for this file would be `copyright.extra`, as it contains all the files and licenses that are not covered by AGPL in the core directory.

The `debian/Makefile` uses this (and other) file to create `debian/copyright`, therefore you have this information twice.

2024-04-08 14:53 UTC, joergsteffens commented on debian/copyright
>  Files: core/src/win32/plugins/filed/mssqlvdi-fd.c
I hoped, that this was covered by 
```
Files: core/* docs/manuals/source/*
Copyright: 2000-2012 Free Software Foundation Europe e.V.
           2010-2017 Planets Communications B.V.
           2012-2024 Bareos GmbH & Co. KG
```
If not, we have to maintain all Copyright Bareos entries every year.

2024-04-09 07:38 UTC, bruno-at-bareos commented
We may want to sort out the building of LICENSE.txt in root related to #1755

2024-04-10 14:26 UTC, bruno-at-bareos commented
As discussed during the meeting, we would like to have this Makefile able to build /LICENSE.txt file 
then debian can have a copy or use the result.

2024-04-10 14:28 UTC, bruno-at-bareos reviewed
While it is ok now, could you handle the /LICENSE.txt generation?

2024-04-10 14:33 UTC, joergsteffens commented
As discussed in the DevMeeting, I'll do a rework and create the LICENSE.txt file.

2024-04-11 14:09 UTC, bruno-at-bareos commented on debian/copyright
So you still want to keep this one as a symlink?

2024-04-11 14:17 UTC, bruno-at-bareos commented on devtools/update-license-file.sh
We may want to improve a bit the code, as ` shellcheck`  complain on several part of it.

2024-04-11 14:33 UTC, bruno-at-bareos commented on cmake/BareosUpdateLicenseFile.cmake
It would maybe also nice to have a line into the cmake result that license.txt will be updated so before running make, you know the -DGENERATE_LICENSE_FILE=ON has been took into account.
Your thoughts?

2024-04-11 14:46 UTC, bruno-at-bareos requested changes
Nice work, we're almost done. 
Please check my comments.

2024-04-11 15:49 UTC, joergsteffens commented on cmake/BareosUpdateLicenseFile.cmake
The file only got overwritten, when you specify  `-DGENERATE_LICENSE_FILE=ON`. I think an extra warning is not required (and @arogge is even unsure, if this cmake option is useful at all).

2024-04-11 15:51 UTC, joergsteffens commented on debian/copyright
Yes, this file is required and debian can cope with this link.

2024-04-15 11:38 UTC, bruno-at-bareos commented on cmake/BareosUpdateLicenseFile.cmake
File deleted

2024-04-15 11:41 UTC, bruno-at-bareos commented on debian/copyright
>  Files: core/src/win32/plugins/filed/mssqlvdi-fd.c
@joergsteffens I've still a question for this file: as the following 
```
Copyright (C) 2010 Zilvinas Krapavickas <zkrapavickas@gmail.com>
```
is not covered by the glob Copyright core/* , but is present in `copyright.extra` we consider it correctly described.

2024-04-15 13:14 UTC, bruno-at-bareos requested changes
With the removal of the cmake target, the README.md in third party need to be fixed.  See suggestion.

2024-04-15 13:14 UTC, bruno-at-bareos commented on third-party/README.md
> +Also execute `make licensefile` to update `LICENSE.txt`.
```suggestion
Also execute `devtools/update-license-file.sh` to update `LICENSE.txt`, and commit new version.
```

2024-04-15 14:12 UTC, bruno-at-bareos commented on debian/copyright
>  Files: core/src/win32/plugins/filed/mssqlvdi-fd.c
We keep it like it is

2024-04-15 14:13 UTC, bruno-at-bareos approved these changes
Thanks nice improvement.

2024-04-15 14:40 UTC, merged