docs: improve handling of ResourceItem descriptions
bareos/bareos pull request #1761
Opened 2024-04-04 09:56 UTC by joergsteffens

### Thank you for contributing to the Bareos Project!

Document and make sure, that ResourceItem descriptions are plain text.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

2024-04-08 14:57 UTC, bruno-at-bareos requested changes
Nicely done, now to be able to build the PR, 
@sebsura do you want to fix the extra openssl command we have in the C code
```
sphinx-build -M html ../b-at-bareos/docs/manuals/source docs/BareosMainReference -j16
Running Sphinx v5.3.0
/bareos/git/b-at-bareos/docs/manuals
INFO generate-resource-descriptions.createSphinx: Create RST/Sphinx files ...
INFO generate-resource-descriptions.__init__: format-version: 2
INFO generate-resource-descriptions.createSphinx: daemon: bareos-dir, resource: Catalog
INFO generate-resource-descriptions.createSphinx: daemon: bareos-dir, resource: Client
Traceback (most recent call last):
  File "scripts/generate-resource-descriptions.py", line 507, in <module>
    createSphinx(data)
  File "scripts/generate-resource-descriptions.py", line 455, in createSphinx
    sphinx.writeResourceDirectives(
  File "scripts/generate-resource-descriptions.py", line 193, in writeResourceDirectives
    self.out.write(self.getConvertedResourceDirectives(daemon, resourcename))
  File "scripts/generate-resource-descriptions.py", line 289, in getConvertedResourceDirectives
    "description": self.getDescription(data),
  File "scripts/generate-resource-descriptions.py", line 264, in getDescription
    raise RuntimeError(f"Description is not plain text: '{description}'")
RuntimeError: Description is not plain text: 'List of valid TLSv1.2 and lower Ciphers; see :command:`openssl ciphers`'

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/bareos/git/b-at-bareos/docs/manuals/source/conf.py", line 417, in <module>
    subprocess.check_call(
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['scripts/generate-resource-descriptions.py', '--sphinx', 'source/include/autogenerated/bareos-dir-config-schema.json']' returned non-zero exit status 1.
```

2024-04-08 17:51 UTC, joergsteffens commented
I did the description changes in a minimal way, by rewriting the description in the C code (`core/src/lib/tls_resource_items.h`). This has the advantage that it is centrally defined and reused in all programs, resulting in 2 changed lines, instead of modifying 30 files.

2024-04-09 14:40 UTC, joergsteffens commented on core/src/lib/tls_resource_items.h
>      " Leftmost element has the highest priority." \
Added the same hint here.

2024-04-09 14:42 UTC, joergsteffens commented on core/src/lib/tls_resource_items.h
>    { "TlsCipherList", CFG_TYPE_STDSTRDIR, ITEM(res, cipherlist_), 0, CFG_ITEM_PLATFORM_SPECIFIC, NULL, \
I fixed it to `CFG_TYPE_STDSTR` (STRING). It is not a Bareos resource list, just a string, separated by columns.

2024-04-09 14:46 UTC, joergsteffens commented
@bruno-at-bareos When you finished your review, I'd like to squash some of the commits together.

2024-04-09 14:47 UTC, bruno-at-bareos approved these changes
Thanks everything looks good now.
I would recommend to backport to 23 (at least) so the rules and the sphinx generator are in place.

to do so, you may want to go for squashing commits first maybe.

2024-04-10 15:34 UTC, merged