cats: fix subscription view missing mariabackup plugin
bareos/bareos pull request #1767
Opened 2024-04-10 15:22 UTC by bruno-at-bareos

- add missing mariabackup plugin
- increase catalog version to 2240
- fix issue #1759 

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-04-25 05:01 UTC, sebsura requested changes
So what about the new `bareos-fd-postgresql` plugin ?  Does this not get counted yet ?

2024-04-25 07:51 UTC, bruno-at-bareos commented on core/src/cats/ddl/updates/postgresql.2230_2240.sql
> +drop index if exists file_jobid_idx;
Yes you're right the explanation being not easy to understand.
I'm adding the why we do that now.
```
-- drop old index file_jobid_idx if still present.
-- replaced by file_jpfid_idx in 2014
-- PostgreSQL is able to use first column of partial index.
-- We can drop it as we only have PG backend.
```

2024-04-25 07:57 UTC, bruno-at-bareos commented on core/src/cats/ddl/creates/postgresql.sql
> +INSERT INTO Version (VersionId) VALUES (2240);
Sorry I don't understand what is the `status` table ?

2024-04-25 07:57 UTC, bruno-at-bareos commented on core/src/cats/ddl/updates/postgresql.2230_2240.sql
> +-- update db schema from 2210 to 2230
oh good catch. done

2024-04-26 09:41 UTC, sebsura commented on core/src/cats/ddl/creates/postgresql.sql
> +INSERT INTO Version (VersionId) VALUES (2240);
its a table that maps status codes to descriptions
```
CREATE TABLE Status (
    JobStatus         CHAR(1)     NOT NULL,
    JobStatusLong     TEXT,
    Severity          INTEGER,
    PRIMARY KEY (JobStatus)
);
```

2024-04-26 09:41 UTC, sebsura commented on core/src/cats/ddl/updates/postgresql.2230_2240.sql
> +drop index if exists file_jobid_idx;
Yep. Thats perfect.

2024-04-26 09:42 UTC, sebsura approved these changes
Good Work!

2024-04-29 05:19 UTC, merged