pr-tool: update LICENSE.txt
bareos/bareos pull request #1773
Opened 2024-04-16 08:43 UTC by joergsteffens

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-04-19 14:10 UTC, arogge requested changes
I found some minor issues with the copyright headers.
Besides that there is a small performance gain possible by omitting an API request and pylint brought up a few remarks.

2024-04-23 13:33 UTC, joergsteffens commented on devtools/pip-tools/license_utils/__init__.py
> +
added.

2024-04-23 13:33 UTC, joergsteffens commented on devtools/pip-tools/license_utils/update_license.py
> +
done.

2024-04-23 13:33 UTC, joergsteffens commented on devtools/pip-tools/license_utils/update_license.py
> +    exit(main())
done.

2024-04-23 13:34 UTC, joergsteffens commented on devtools/pip-tools/pr_tool/main.py
> +            exit(1)
Good point. Moved it to an earlier stage.

2024-04-23 13:34 UTC, joergsteffens commented on devtools/pip-tools/license_utils/__init__.py
> +#   Copyright (C) 202-2024 Bareos GmbH & Co. KG
done.

2024-04-23 13:34 UTC, joergsteffens commented on devtools/pip-tools/setup.py
> +            "update-license=license_utils.update_license:main",
done.

2024-05-08 13:26 UTC, joergsteffens commented
I just discovered. that github now has 2 License entries. I assume, one for LICENSE.txt and on for LICENSE.template (https://github.com/bareos/bareos?tab=License-2-ov-file).
I  assume, it is best, if I move the tempate file to another directory or rename the file.

2024-05-17 13:25 UTC, merged