windows: fix some crashes, change handling of invalid paths; lex: add better error detection; accurate: fix out of bounds writes
bareos/bareos pull request #1793
Opened 2024-04-29 06:10 UTC by sebsura

### Thank you for contributing to the Bareos Project!

This PR contains the following changes:
* accurate: fix out of bounds writes in rare circumstances
* compression: remove use of thread_local, which may lead to a crash (delete after free) on windows
* message: fix trying to call `/usr/bin/sendmail` on windows
* windows: replace deprecated `SHGetFolderPath` by `SHGetKnownFolderPath`
* windows: fix support for invalid paths

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-05-02 08:17 UTC, bruno-at-bareos commented
This has fixed issues encountered in support ticket 75261.

2024-05-16 10:56 UTC, sebsura commented on core/src/filed/accurate.h
> +    seen_bitmap_[payload->filenr] = true;
add comment explaining this

2024-05-16 11:19 UTC, pstorz requested changes
As spoken

2024-05-16 11:19 UTC, sebsura commented on systemtests/tests/accurate-stresstest/testrunner-file-miscount
> +@$out $log_home/query.out
add test for lmdb as well + add doc string for lmdb options.

2024-05-27 09:29 UTC, sebsura commented on systemtests/tests/accurate-stresstest/testrunner-file-miscount
> +@$out $log_home/query.out
done

2024-05-27 09:30 UTC, sebsura commented on core/src/filed/accurate.h
> +    seen_bitmap_[payload->filenr] = true;
done

2024-05-28 13:52 UTC, pstorz requested changes, later dismissed
Please see comments,

The accurate-lmdb tests still fail as already talked about.

2024-05-28 13:52 UTC, pstorz commented on docs/manuals/source/manually_added_config_directive_descriptions/fd-client-MaximumWorkersPerJob.rst.inc
> +   If this is set to at least 1, then bareos will use a seperate thread for sending data.
```suggestion
   If this is set to at least 1, bareos will use a separate thread for sending data.
```

2024-05-29 11:36 UTC, sebsura commented on docs/manuals/source/manually_added_config_directive_descriptions/fd-client-MaximumWorkersPerJob.rst.inc
> +   If this is set to at least 1, then bareos will use a seperate thread for sending data.
done

2024-06-18 14:36 UTC, pstorz approved these changes

2024-06-20 13:21 UTC, merged