bsmtp: add fixes to be more rfc compliant
bareos/bareos pull request #1795
Opened 2024-04-29 14:42 UTC by bruno-at-bareos

- add mime version
- add content type and charset
- add content transport encoding
- right trim subject

those fixes should help bsmtp to lower spam score
avoid using utf-8 subject, it's rfc2047 encoding not being implemented.

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-04-30 09:56 UTC, bruno-at-bareos commented
Still to be done: 
- add mailx usage documentation in howto

2024-05-07 14:07 UTC, bruno-at-bareos commented
Recommendation tested by customer and `mailx` replacement got good result in terms of scoring. `bstmp` changes are also welcomed.

2024-05-13 21:09 UTC, sduehr requested changes
Thanks, looks good so far, some typos to be fixed.

2024-05-13 21:09 UTC, sduehr commented on docs/manuals/source/Appendix/Howtos/UseMailxAsBsmtpReplacement.rst.inc
> +   .. code-block:: shell-session
```suggestion
.. code-block:: shell-session
```

2024-05-13 21:09 UTC, sduehr commented on docs/manuals/source/Appendix/Howtos/UseMailxAsBsmtpReplacement.rst.inc
> +This file allow to use sensitive data without leaking them on command line, but you can also set
```suggestion
This file allows to use sensitive data without leaking them on command line, but you can also set
```

2024-05-13 21:09 UTC, sduehr commented on docs/manuals/source/Appendix/Howtos/UseMailxAsBsmtpReplacement.rst.inc
> +   have an interest in your infrastructure.
```suggestion
   be relevant in your infrastructure.
```

2024-05-13 21:09 UTC, sduehr commented on docs/manuals/source/Appendix/Howtos/UseMailxAsBsmtpReplacement.rst.inc
> +There is several ways to check if errors occurred during mail transport with :command:`mailx`.
```suggestion
There are several ways to check if errors occurred during mail transport with :command:`mailx`.
```

2024-05-13 21:09 UTC, sduehr commented on docs/manuals/source/Appendix/Howtos/UseMailxAsBsmtpReplacement.rst.inc
> +With :command:`systemd` managed hosts, the |dir| service will log error that happen.
```suggestion
On :command:`systemd` managed hosts, the |dir| service will log errors that occur.
```

2024-05-14 07:20 UTC, bruno-at-bareos commented
Thanks a lot for the review, and nice rewording.

2024-05-16 18:27 UTC, sduehr approved these changes
Thanks, looks good now.

2024-05-17 07:29 UTC, merged