alist: fix race condition while iterating
bareos/bareos pull request #1859
Opened 2024-06-20 11:51 UTC by sebsura

This pr fixes a race condition that happens when iterating over the same alist concurrently.  This is done by rippping out the internal iterator state and using extrernal ones.  Specifically we now use a simple pointer pair similar to std::vector.

### Thank you for contributing to the Bareos Project!

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-07-01 12:17 UTC, arogge requested changes
I think we should preserve the ability to loop over a `NULL` `alist<T>*`. We just need free function templates for that which will also eliminate the need to dereference the `alist<T>*` before giving it to `for()`.

2024-07-01 12:20 UTC, sebsura commented on core/src/lib/alist.h
> +
Great point!  I totally missed the fact that you can specify begin/end as free functions.

2024-07-08 07:36 UTC, sebsura commented on core/src/lib/alist.h
> +
I replaced
```
if (x) for ( ... : *x )
```
with just
```
for ( ... : x )
```
but i left it as
```
for ( ... : *x )
```
in cases where we know that `x` is nonnull.

2024-07-19 08:31 UTC, arogge approved these changes
Great work! It is incredible how much simpler a lot of the code suddenly looks with just that simple change...

2024-07-19 09:59 UTC, merged