Improved documentation about Catalog restore process.
bareos/bareos pull request #1878
Opened 2024-07-02 13:51 UTC by UraniumDonut

- Added a point about importing the Catalog Backup.
- Changed the next point to be syntactially correct.

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-07-02 14:58 UTC, bruno-at-bareos requested changes
Thanks for your suggestion, I've a slightly different fix  you may want to apply.

2024-07-02 14:58 UTC, bruno-at-bareos commented on docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
> +-  After the Catalog is restored, it should be located in (:file:`./var/lib/bareos/bareos.sql`) relative to the restore location. After stopping the bareos-dir service, his file then needs to be load
I would slightly fix the comment by this formulation.

```suggestion
-  After the Catalog is restored, it should be located in (:file:`./var/lib/bareos/bareos.sql`) relative to the restore location. After stopping the bareos-dir service, this file then needs to be loaded into the PostgreSQL database. (For example by running ``sudo -u bareos psql bareos bareos -f ./var/lib/bareos/bareos.sql`` or ```su postgres -c "psql bareos -f ./var/lib/bareos/bareos.sql``)
```

2024-07-04 11:10 UTC, bruno-at-bareos commented
Also now the build doc has tried there's some failures you want to fix

```

2024-07-04 11:35 UTC, UraniumDonut commented
Thanks for the hints!
As I have no idea how to edit existing commit messages, I will re-open a new PR with the new changes and proper line endings.

2024-07-04 12:33 UTC, bruno-at-bareos commented
Reopened, fixes will goes there as all the other parameters are already in place. (tagging project labels etc)

2024-07-04 12:42 UTC, bruno-at-bareos commented
We are working on a way to allow external contributor to have access to build result, I will take care of the message after your submission.

2024-07-04 12:56 UTC, bruno-at-bareos commented
We have this section into the documentation that may help 
https://docs.bareos.org/master/DeveloperGuide/gitworkflow.html#commit-message-guideline

For example your commit to the rst can have as subject
```
doc: improve section recovering Bareos server section
```
With a body like 
```
Add examples how to load the restored database ascii dump as catalog.
``` 
So the subject is short enough (around 50 char) but explicit for the changelog.
(you may want to consult the existing to find similar commit)

Once you have it done, you should also modify the title pr here so it can be also used during the merge.
Don't hesitate to ask help if needed.

2024-07-05 15:49 UTC, UraniumDonut commented
I think I managed to change it properly. Thanks for all the tips, I already learned a lot more about git!

2024-07-08 06:59 UTC, UraniumDonut commented
Still failing :/

2024-07-08 07:30 UTC, bruno-at-bareos commented
> Build still failing :/

No in fact, the final review is now needed (which I will take care of today).

2024-07-08 07:49 UTC, bruno-at-bareos commented
> > Build still failing :/
> 
> No in fact, the final review is now needed (which I will take care of today).

And I will fix the warning of our pr-tool
Commit checks failed:
 	b2401123f docs: improve section recovering Bareos server section: body contains line longer 72 chars

If you want to contribute more, it will be interesting to setup a dev environment (see documentation it should be complete), you will find our tools in the devtools subdir.

2024-07-08 08:16 UTC, bruno-at-bareos approved these changes
Thanks for the work, Approved.

2024-07-08 09:38 UTC, merged

2024-07-08 10:57 UTC, UraniumDonut commented
Thanks for the help!