matrix remove obsolete SUSE
bareos/bareos pull request #1888
Opened 2024-07-08 13:58 UTC by bruno-at-bareos

- **matrix.yml: remove end of life SUSE/Leap**
- **tests: postgresql increase start timeout to 15**

### Thank you for contributing to the Bareos Project!

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-07-09 07:45 UTC, arogge commented
I want this! :)
I think we should also backport this into Bareos 23 and 22 (which should be trivial)

2024-07-09 07:46 UTC, arogge approved these changes

2024-07-09 08:53 UTC, bruno-at-bareos commented
> I want this! :) I think we should also backport this into Bareos 23 and 22 (which should be trivial)

So it mean I just got a green light to update my CD-Buildimage branch to make ready of 156 :-)
I will prepare that.

2024-07-31 08:28 UTC, sebsura requested changes

2024-07-31 08:28 UTC, sebsura commented on systemtests/tests/py3plug-fd-mariabackup/testrunner-default
> +
We should not do this.  People running our tests do not expect us to potentially destroy their configurations.  Lets see if this is really needed.

2024-08-01 08:08 UTC, sebsura approved these changes
ALGTM

2024-08-01 14:08 UTC, merged