Refactor some Xattr and Acl internals
bareos/bareos pull request #1893
Opened 2024-07-12 11:04 UTC by arogge

This is my approach to use proper C++ types instead of pointer-connected C structs for XattrData (and maybe AclData).
This will also fix a crash when running bextract to extract a job with xattr onto a filesystem without xattr support (and presumably the same for acl data).

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-07-17 12:07 UTC, sebsura requested changes
Looks like a very good change to me. I just found one typo that needs fixing.

2024-07-17 12:07 UTC, sebsura commented on core/src/findlib/xattr.cc
> +    XattrBXattrBuildData* xattr_data,
On another note: it looks like the xattr caching is just done on solaris.  Was it really slow on those platforms or why is this not done elsewhere ?

I currently dont see the need to remove this but i feel like this is a lot of code for probably very little upside.

2024-10-22 10:50 UTC, sebsura commented on core/src/findlib/xattr.cc
> +    XattrBXattrBuildData* xattr_data,
pretty sure this should be XattrBuildData looking at the rest of the code

2024-12-18 13:25 UTC, arogge commented on core/src/findlib/xattr.cc
> +    XattrBXattrBuildData* xattr_data,
So I just looked into extended attributes on Solaris. These work basically much like alternate file streams on Windows. You can `openat()` with an fd pointing to an open file to access the attribute.
And that attribute-file then can have attribute-files and each of these has its own stat-block and ACL records.

Nevertheless, if we decide to revive the Solaris build, we should probably measure how slow this is in the real world. We can then decide if we want to keep that complexity or not.

2024-12-18 13:27 UTC, arogge commented on core/src/findlib/xattr.cc
> +    XattrBXattrBuildData* xattr_data,
and I fixed that name, of course.

2024-12-20 10:17 UTC, sebsura commented on core/src/findlib/acl.h
> +static constexpr uint32_t BACL_FLAG_RESTORE_AFS = 0x08;
```suggestion
inline constexpr uint32_t BACL_FLAG_SAVE_NATIVE = 0x01;
inline constexpr uint32_t BACL_FLAG_SAVE_AFS = 0x02;
inline constexpr uint32_t BACL_FLAG_RESTORE_NATIVE = 0x04;
inline constexpr uint32_t BACL_FLAG_RESTORE_AFS = 0x08;
```

2024-12-20 10:18 UTC, sebsura commented on core/src/findlib/acl.h
> +static constexpr uint32_t ACL_REPORT_ERR_MAX_PER_JOB = 25;
```suggestion
inline constexpr uint32_t ACL_REPORT_ERR_MAX_PER_JOB = 25;
```

2024-12-20 13:56 UTC, arogge commented
I also added two small changes for things that bugged my in the windows build.

2025-01-06 08:06 UTC, sebsura requested changes
The new changes are really great!

I added some small remarks, but this is basically good to go!

2025-01-06 08:06 UTC, sebsura commented on core/src/findlib/xattr.cc
> +          xattr_data->last_fname);
For our own sanity: We should also print the reason here, e.g.:
```C
"(%" PRIu32 " < %" PRIu32 ")", ..., serialize_len, expected_serialize_len
```
(or just %lu if the printf pr is not merged yet)

2025-01-06 08:06 UTC, sebsura commented on core/src/findlib/xattr.cc
> +  if (serialize_len < expected_serialize_len) {
Technically the `SerEnd` in `SerializeXattrStream` should already catch the `>` case, but just in case i would use `!=` here.

2025-01-06 15:38 UTC, arogge commented on cmake/BareosGenerateDebianInfo.cmake
> +
At least on Univention and Ubuntu, but also when testing changes on other machines (i.e. you might not want to start a debian container/VM just to check a trivial change)

2025-01-06 17:07 UTC, arogge commented on core/src/findlib/xattr.cc
> +  if (serialize_len < expected_serialize_len) {
Maybe `SerializeXattrStream()` should just return `xattr_data->content_length == expected_serialize_len` instead of `xattr_data->content_length`.

2025-01-08 10:23 UTC, sebsura requested changes

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>    /* See if the BACL_FLAG_SAVE_NATIVE flag is set which lets us know if we
update the comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>    /* See if the BACL_FLAG_SAVE_AFS flag is set which lets us know if we should
same here

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>       * BACL_FLAG_SAVE_NATIVE flag. */
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>             * files on the same filesystem. The BACL_FLAG_RESTORE_NATIVE flag
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>         * when we change from one filesystem to another. */
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>         * set again when we change from one filesystem to another. */
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>           * set again when we change from one filesystem to another. */
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>           * when we change from one filesystem to another. */
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>           * set again when we change from one filesystem to another. */
update comment

2025-01-08 10:23 UTC, sebsura commented on core/src/findlib/acl.cc
>     * when we change from one filesystem to another. */
update comment

2025-01-09 06:10 UTC, sebsura approved these changes

2025-02-11 08:30 UTC, merged