matrix remove obsolete SUSE
bareos/bareos pull request #1907
Opened 2024-07-30 11:57 UTC by bruno-at-bareos

**Backport of PR #1888 to bareos-22**

Added commit 68710b7960 backporting mtx-changer without perl.

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Correct milestone is set

##### Source code quality (if there were changes to the original PR)
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

#### Backport quality
- [ ] Original PR #1888 is merged
- [ ] All functional differences to the original PR are documented above

2024-07-31 09:29 UTC, sebsura requested changes

2024-07-31 09:29 UTC, sebsura commented on core/platforms/packaging/bareos.spec
> +CXX=g++-13 ; export CXX
This needs to be reverted / adjusted

2024-07-31 09:30 UTC, sebsura commented on core/platforms/packaging/bareos.spec
> +CXX=g++-13 ; export CXX
otherwise it wont build on sles12

2024-07-31 09:30 UTC, sebsura commented on core/platforms/packaging/bareos.spec
> +BuildRequires: gcc13-c++
Same here

2024-07-31 15:18 UTC, bruno-at-bareos commented on core/platforms/packaging/bareos.spec
> +BuildRequires: gcc13-c++
same here

2024-08-02 05:34 UTC, sebsura requested changes
Dont forget to re-cherrypick from the actually merged version of https://github.com/bareos/bareos/pull/1888

2024-08-08 11:53 UTC, sebsura approved these changes

2024-08-13 06:49 UTC, merged