systemtest fix plugin old postgres and newer postgresql
bareos/bareos pull request #1948
Opened 2024-09-03 15:06 UTC by bruno-at-bareos

in this PR we propose to backport to changes made in newer postgresql plugin, fix debian pg_version awk detection, and also skip debian test if not root.

to fix issue during build and testing the old postgres plugin, we replaced the calls of `bc` tool by simple sh expressions.

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-09-19 15:41 UTC, joergsteffens requested changes
Generally this looks good, only two minor remarks left.

2024-09-19 15:41 UTC, joergsteffens commented on systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh.in
There is no need (anymore) that this file is a `*.in` file.

2024-09-23 09:00 UTC, bruno-at-bareos commented on systemtests/tests/py3plug-fd-postgresql/testrunner-debian
> +PG_VERSION=$(pg_lsclusters | awk -F " " '/^[0-9]{1,} .*/ {print $1}')
`psql` version is not really useful as the tool can connect to any pg => to it.
Your deterministic approach with `pg_lsclusters` while still perfectible is more what we want to test here. I will upport this to #1947 first then include it here as backport.

2024-09-23 09:00 UTC, bruno-at-bareos commented on systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh.in
Nice catch, will do that also in #1947 and make the backport here.

2024-09-25 08:30 UTC, bruno-at-bareos commented on systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh.in
done

2024-09-25 08:33 UTC, bruno-at-bareos commented on systemtests/tests/py3plug-fd-postgresql/testrunner-debian
> +PG_VERSION=$(pg_lsclusters | awk -F " " '/^[0-9]{1,} .*/ {print $1}')
fixed

2024-09-25 08:56 UTC, joergsteffens approved these changes

2024-09-25 09:14 UTC, merged