use CPM packages instead of third-party directory
bareos/bareos pull request #1963
Opened 2024-09-24 14:46 UTC by arogge

This is an alternative PR to #1911

* write a cpm-packages.yaml with a bit of metadata to `$CMAKE_BINARY_DIR`
* add a `CPM_ONLY`-mode to our CMake, so you can run only CPM
* extend update_license.py to grab the licenses of the CPM packages
* replace (and update) all third-party dependencies with CPM packages
* update all pip-tools
* fix some minor issues (fastlz, truncate systemtest)

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2024-10-08 14:45 UTC, pstorz approved these changes
Looks good to me

2024-10-08 14:45 UTC, pstorz commented on debian/control
> +Description: Backup Archiving Recovery Open Sourced - storage daemon DEDUP backend
```suggestion
Description: Backup Archiving Recovery Open Sourced - storage daemon DEDUPABLE backend
```

2024-10-08 14:45 UTC, pstorz commented on debian/control
> + This package contains the Storage backend for DEDUP files.
```suggestion
 This package contains the Storage backend for DEDUPABLE files.
```

2024-10-08 14:46 UTC, pstorz requested changes
See comments

2024-10-11 09:51 UTC, arogge commented on debian/control
> +Description: Backup Archiving Recovery Open Sourced - storage daemon DEDUP backend
fixed in #1977 and #1978

2024-10-11 09:52 UTC, arogge commented on debian/control
> + This package contains the Storage backend for DEDUP files.
fixed in #1977 and #1978

2024-10-22 12:02 UTC, arogge commented
The changes you requested were handled in PR #1977 and #1978.

2024-10-23 07:40 UTC, pstorz approved these changes

2024-10-23 08:34 UTC, merged