mssqlvdi-fd: add support for filestream backups
bareos/bareos pull request #2072
Opened 2024-12-17 09:56 UTC by sebsura

### Thank you for contributing to the Bareos Project!

The plugin was written during a time where the `VDC_Flush` command was only emitted at the end of a backup.
This caused our logic to conflate the two: whenever `VDC_Flush` was requested, we told the core (implicitly by returning count=0 from read) that the single file we backup is done.

As mentioned in this [article](https://techcommunity.microsoft.com/blog/sqlserver/introducing-vdc-complete-for-backup-and-restore-applications-using-sqlvdi/385126) this is (and was) always a bad assumption.

Fixing this without changing the complete logic of the plugin was hard, but thanks to the introduction of the `VDC_Complete` command it was possible.

The way it works is like so:  When starting a backup, we request from the vdi device that it should notify us when the backup is complete by setting `VDF_RequestComplete` in the configuration.
If this succeeds (`completion_support = true`) then during IO operations we ignore `VDC_Flush` and continue on until we hit `VDC_Complete` at which point we actually tell the core that we are done.

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [ ] Is the PR title usable as CHANGELOG entry?
- [ ] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR

##### Tests
- [ ] Decision taken that a test is required (if not, then remove this paragraph)
- [ ] The choice of the type of test (unit test or systemtest) is reasonable
- [ ] Testname matches exactly what is being tested
- [ ] On a fail, output of the test leads quickly to the origin of the fault

2025-02-13 06:22 UTC, sebsura reviewed
We should also have a test that actually back ups/ restores a filestream object.

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
> +   #File = "@sbindir@"
delete

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
> +      fstype = vfat
Delete (its wrong anyways, as windows uses ntfs)

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-fd.d/client/myself.conf.in
> +  #
delete

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-sd.d/device/FileStorage.conf
> +  Auto Deflate Algorithm = gzip
delete

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-sd.d/device/FileStorage2.conf
> +  Auto Deflate Algorithm = lz4
Delete

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-sd.d/device/FileStorage2.conf
> +  Name = FileStorage2
The director cannot even use this device, so we should just delete it.

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
> +  #
Delete

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
> +  Plugin Names = "autoxflate"
delete as well, there is no need to test autoxflate in this test

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
> +  ## @sd_backend_config@ ##
delete

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/sqlfiles/SQL_create_bareos_login_user.sql
> +--go
What do we need these comments for ?

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/sqlfiles/SQL_add_data.sql
> +USE [$(myDB)]
Should we add a copyright notice do these files or is that not necessary ?

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-01-DBNormal-prepare
> +set -x
Was this used to test the test, or is this helpful when viewed on jenkins ?

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-01-DBNormal-prepare
> +
Should this not have `start_test` and `end_test` ?

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-02-DBNormal-FullBackup
> +fi
please use `expect_grep` and `expect_not_grep`

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-03-DBNormal-IncBackup
> +fi
Same here

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-04-DBNormal-DropDB
> +
start_test/end_test

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-05-DBNormal-Restore
> +echo "$0" >"${tmp}/data/$myname"
Im not sure why this is done.  Could you add a comment explaining this ?

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-11-DBFileStream-prepare
> +set -x
Same as before: why is this set, also no start_test/end_test

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-12-DBFileStream-FullBackup
> +echo "$0" >"${tmp}/data/$myname"
see above

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-12-DBFileStream-FullBackup
> +fi
see above

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-13-DBFileStream-IncBackup
> +fi
see above

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-14-DBFileStream-DropDB
> +
start_test/end_test

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-15-DBFileStream-Restore
> +set -x
see above

2025-02-13 06:22 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-15-DBFileStream-Restore
> +
see above

2025-02-13 08:19 UTC, pstorz commented on systemtests/tests/mssqlvdi-plugin/CMakeLists.txt
> +systemtest_requires(02-DBNormal-FullBackup 01-DBNormal-prepare)
Probably it makes sense to unify all tests to be like that.

2025-02-13 08:22 UTC, pstorz commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
> +  # Plugin Names = ""
Make sense

2025-02-13 08:42 UTC, pstorz commented on systemtests/tests/mssqlvdi-plugin/testrunner-04-DBNormal-DropDB
> +
See above

2025-02-13 08:46 UTC, pstorz commented on systemtests/tests/mssqlvdi-plugin/testrunner-14-DBFileStream-DropDB
> +
see above

2025-02-17 13:18 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/sqlfiles/SQL_add_data.sql
> +USE [$(myDB)]
Now we will, as they are our own examples. Thanks for pointing this.

2025-02-20 15:19 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/testrunner-15-DBFileStream-Restore
> +set -x
done

2025-03-03 15:37 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/testrunner-15-DBFileStream-Restore
> +set -x
> @bruno-at-bareos you said its done, but it still looks to be here. What i meant was the `set -x` call. Sorry for the confusion!

oh thanks to have took care of it.

2025-03-17 09:49 UTC, bruno-at-bareos requested changes
In this last review I've added or confirmed some request changes asked by @sebsura 
A complete manual test on a separated host with database with other name has been successfully backup-ed and restored. Especially checked the recreation of the Attachment folder.

2025-03-17 09:49 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/pool/purgeoldest.conf
Why are we keeping those ?
```suggestion

```

2025-03-17 09:49 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/pool/quickrecycle.conf
Why are keeping this one too ?
```suggestion

```

2025-03-17 09:49 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
> +  Subscriptions = 10
Nope you're right.

```suggestion
```

2025-03-17 09:49 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/storage/File.conf.in
> +  SD Port = @sd_port@
```suggestion
  Port = @sd_port@
```
New configuration, but can be problematic in case of backport.

2025-03-17 09:49 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
> +  FD PORT = @fd_port@
```suggestion
  PORT = @fd_port@
```
Avoid warnings, but think about it in case of backport to 24

2025-03-17 09:49 UTC, bruno-at-bareos commented on CMakeLists.txt
> +if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.31")
Do we still need this one?
We normally have already done the upgrade to 3.31 in #2169

2025-03-24 09:55 UTC, bruno-at-bareos requested changes
We're almost done. I requested a few changes please check them.

2025-03-24 09:55 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/test-setup
> +# "${SQLCMD}" -S "${COMPUTERNAME}" -E -b -i sqlfiles/SQL_grant_sysadmin_role.sql
Shouldn't we have it always uncomment, as it should be error proof with the use of `if not exist`?
```suggestion 
"${SQLCMD}" -S "${COMPUTERNAME}" -E -b -i sqlfiles/SQL_grant_sysadmin_role.sql
```

2025-03-24 09:55 UTC, bruno-at-bareos commented on cmake/BareosTargetTools.cmake
> +    else()
Stupid question if we catch exe and shared lib in the if, what kind of stuff will go to LIBRARY_OUTPUT_DIRECTORY ?

2025-03-24 09:55 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/sqlfiles/SQL_db_filestream_drop_create.sql
Please rename the file. The drop being done in test-cleanup and test-setup with the new unified call.
Restore test should also be checked, to call the unified drop_db.

2025-03-24 09:55 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/sqlfiles/SQL_db_normal_drop_create.sql
Please rename the file. The drop being done in test-cleanup and test-setup with the new unified call.
Restore test should also be checked, to call the unified drop_db.

2025-03-24 09:55 UTC, bruno-at-bareos commented on systemtests/tests/mssqlvdi-plugin/sqlfiles/SQL_drop_tables_schemas.sql
As we drop completely the DB, I don't think we're using that file. So it can be removed completely.

```suggestion
```

2025-03-24 10:06 UTC, sebsura commented on cmake/BareosTargetTools.cmake
> +    else()
Plugins have type `MODULE_LIBRARY`.  These get put to the LIBRARY_OUTPUT_DIRECTORY.

2025-03-24 10:10 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/environment.local
> +#
What would you like to get explained in the header ?

2025-03-24 10:10 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/environment.local
> +#
I guess i can explain what these variables are for.

2025-03-24 10:12 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/test-setup
> +# "${SQLCMD}" -S "${COMPUTERNAME}" -E -b -i sqlfiles/SQL_grant_sysadmin_role.sql
I didnt want to do this automatically in case somebody runs the test on a real system.

2025-03-24 10:23 UTC, sebsura commented on systemtests/tests/mssqlvdi-plugin/testrunner-01-DBNormal-prepare
> +start_test
start_test/end_test setup the trap that exists the test on failure as well as output the start/end messages, i.e.
```
=== scheduler: starting at 10:25:37 ===
=
=
```
and
```
  !!!!! scheduler failed!!! 10:26:52 !!!!! 
   Status: zombie=0 backup=2 restore=0 diff=0
  !!!!! Bad termination status       !!!!! 
   Status: backup=2 restore=0 diff=0
```

As they arent harmful i would just keep them in.

2025-03-24 10:37 UTC, bruno-at-bareos commented on CMakeLists.txt
> +if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.31")
Tested and work well here. no warnings or whatever. so closing

2025-03-24 10:38 UTC, bruno-at-bareos commented on cmake/BareosTargetTools.cmake
> +    else()
Thanks.

2025-03-26 09:09 UTC, bruno-at-bareos approved these changes
final review, with approval.

2025-03-26 13:10 UTC, merged