config: add virtual file changer example + documentation
bareos/bareos pull request #2090
Opened 2024-12-24 15:50 UTC by bruno-at-bareos

This PR aims to introduce configuration example files for using an
autochanger with virtual disk autonumbered devices.

We also revisit some related chapter of the documentation.
 
- **device_resource.cc: fix typo and alignment**
- **config: add virtual disk changer to default configuration**
- **doc: update indexes syntax, rewrap paragraph**
- **doc: volume management chapter improvement**

After first presentation (2024-01-14), we want to rename disk to file, to respect the rest of the configuration CamelCase should be used, but it is not as practical and equivalent our tape changer is all lowercase.
We want to avoid name finishing with -

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created
- [x] Correct milestone is set

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

##### TODO
- [x] Installed the packages and enabled the example files to see if it works

2025-02-03 16:03 UTC, pstorz requested changes
Unfortunately was not able to install as we do not have current packages.

2025-02-04 08:45 UTC, bruno-at-bareos commented on core/src/stored/backends/unix_file_device.d/bareos-dir.d/storage/Filechanger.conf.example
> +  Maximum Concurrent Jobs = 10
Sorry but I believe that `storage->device->vfile` is still valid, we changed the default to 1 but it is still in used. I guess you mixed with `storage->storage`
And here the remark is about the `count` parameter if you declare count = 10 and here put 5 only 5 device will in used.

2025-02-04 08:46 UTC, bruno-at-bareos commented on core/src/stored/backends/unix_file_device.d/bareos-sd.d/autochanger/FilechangerStorage.conf.example
> + # We don't have a real changer
top.

2025-02-04 08:46 UTC, bruno-at-bareos commented on core/src/stored/backends/unix_file_device.d/bareos-sd.d/autochanger/FilechangerStorage.conf.example
> + # we use the autonumbering bareos function for that.
top

2025-02-04 08:50 UTC, bruno-at-bareos commented
> Unfortunately was not able to install as we do not have current packages.

With your proposed changes a rebuild has been triggered, so packages should be available today.

2025-02-10 14:57 UTC, wizhippo commented
This configuration has the initial device "vfile0000" "reserved for storage and labeling".

Testing I did a restore and it used vfile0001 by default with no option given to select the reserved device.  Is this expected?  How is the reserved device used?  Does a restore job need to be created that takes advantage of this reserved device?  Does it only come into play if none of the vfile0001 - vfile0xxx are available and it then will let you mount the revered device?

Perhaps a some documentation could be added to clarify its use?

2025-02-10 15:58 UTC, bruno-at-bareos commented
> Unfortunately was not able to install as we do not have current packages.
@pstorz New packages have been created on Feb 10th.

2025-02-10 16:11 UTC, bruno-at-bareos commented
> This configuration has the initial device "vfile0000" "reserved for storage and labeling".
> 
> Testing I did a restore and it used vfile0001 by default with no option given to select the reserved device. Is this expected? How is the reserved device used? Does a restore job need to be created that takes advantage of this reserved device? Does it only come into play if none of the vfile0001 - vfile0xxx are available and it then will let you mount the revered device?
> 
> Perhaps a some documentation could be added to clarify its use?

Interesting comment, I will have a check

2025-03-03 15:50 UTC, bruno-at-bareos reviewed
I don't think that renaming to `File` will improve the situation.
My vote is against for the reason given in the review

2025-03-03 15:50 UTC, bruno-at-bareos commented on core/src/stored/backends/unix_file_device.d/bareos-dir.d/storage/Filechanger.conf.example.in
> +  Name = File # Not named "Filechanger" so that it can replace the default single File storage
If you change again the Name, then it destroy the whole coherency of the examples
Then why not renaming also the File to File.conf.example so it can really replace the default ? But then you also have to change the whole just written documentation to again make it coherent, explicit and actionable)

To me this commit will again just make people at the end confused again.

If at the end, they really want to call it `File` while it is a virtual file changer, that's no more our concern.

2025-03-27 14:44 UTC, bruno-at-bareos commented
Important commit for documentation and defaultconfig not directly related are now extracted and presented in #2225

2025-04-14 13:04 UTC, bruno-at-bareos commented
Today meeting we decided to setup the example and the configuration, like it was done to replace the default distributed `File` and `FileStorage` allowing end user to switch in place jobs without touching any further their configuration.

2025-04-16 07:15 UTC, pstorz approved these changes
Very good work! Thank you bruno.

2025-04-16 12:34 UTC, merged