Fix no "Available versions" in restore dialog for Filenames with spaces
bareos/bareos pull request #576
Opened 2020-08-21 12:34 UTC by MSP-Stev

https://bugs.bareos.org/view.php?id=1265

2020-08-24 08:28 UTC, arogge commented
Would you mind testing this with a file that has a double-quotes in the name? It looks like that might be broken, too.

2020-09-01 13:49 UTC, fbergkemper requested changes
Thanks for the contribution. Can you please apply the suggested change?

2020-09-01 13:49 UTC, fbergkemper commented on webui/module/Restore/src/Restore/Model/RestoreModel.php
> +         $cmd = '.bvfs_versions jobid=0 client='.$clientname.' pathid='.$pathid.' fname="'.$filename.'"';
```suggestion
         $cmd = '.bvfs_versions jobid=0 client='.$clientname.' pathid='.$pathid.' fname="'.addslashes($filename).'"';
```
We should add backslashes before characters that need to be escaped in the fname string, too.

2020-09-10 09:36 UTC, fbergkemper commented
Suggestion applied by an additional commit.

2020-09-10 09:38 UTC, fbergkemper commented
MSP-Stev, if you would like to get mentioned in the Authors file with your real name, please let us know by a comment here.

2020-09-10 09:40 UTC, merged

2020-09-10 09:42 UTC, MSP-Stev commented
Sorry for the late response. i will test your suggestion on our system. my name is Stev Dubau :)

2020-09-10 09:50 UTC, fbergkemper commented
No problem, Stev. Going to add you to the Authors file, thanks again for the contribution.

2020-09-10 09:51 UTC, MSP-Stev commented
you are welcome.