python3: packaging of new python3 plugins
bareos/bareos pull request #597
Opened 2020-09-15 10:28 UTC by pstorz

2020-09-25 12:15 UTC, arogge requested changes
I think we really need to give the python dependencies a thought. Do we want to default to python3? How can we achieve this?
Find my other comments inline.

2020-09-25 12:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Requires:   bareos-director-python-plugins-common = %{version}
If you want the python-based-plugins to depend on the python-c-plugin, you will need a common virtual capability provided by both `*-python-plugin` and `*-python3-plugin` packages each and require that capability in the plugin packages.

However, historically `yum`'s depsolver (I'm not sure if `dnf` is the same) always selects the package with the shortest name when selecting the package to fulfil a dependency. This had been introduced to make sure we do not install a `*-debuginfo` package that would fulfill the dependency.
With the current naming scheme (i.e. `python` vs. `python3` you will most likely end up with the python2 plugin installed (at least on RHEL 7).

2020-09-25 12:15 UTC, arogge commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
shouldn't we reflect this change in the RPM BuildRequires and the Debian pendant, too?

2020-10-02 16:34 UTC, arogge reviewed
Look good. I'd opt for some manual testing. Also I think there are pkglists that are not correct. Probably mostly for systems we no longer build for (e.g. CentOS/RHEL 6, Debian 8, etc.). It is probably best to remove these.

2020-10-02 16:34 UTC, arogge commented on docs/pkglists/CentOS_6.x86_64
>  x86_64/bareos-filedaemon
are the common packages missing? i.e. `bareos-director-python-plugins-common` from the build?

2020-10-02 16:34 UTC, arogge commented on docs/pkglists/Debian_8.0.i586
>  i386/bareos-filedaemon
is the common package missing here?

2020-10-02 16:34 UTC, arogge commented on docs/pkglists/Debian_8.0.x86_64
>  amd64/bareos-filedaemon
is the common package missing here?

2020-10-02 16:34 UTC, arogge commented on docs/pkglists/Fedora_29.x86_64
>  debug/x86_64/bareos-debuginfo
I belive we're not building Fedora 29 anymore. So maybe we could remove pkglist?

2020-10-05 07:50 UTC, pstorz commented
Good point, removed the pkglists of OS we do not build anymore.

2020-10-05 09:15 UTC, arogge requested changes
Installation on RHEL 8 doesn't work.
Provided name doesn't contain "bareos-" Prefix.

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  director-python-plugin
shoud be "bareos-director-python-plugin"

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  director-python-plugin
```suggestion
Provides:   bareos-director-python-plugin
Obsoletes:  bareos-director-python-plugin
```

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  director-python-plugin
```suggestion
Provides:   bareos-director-python-plugin
Obsoletes:  bareos-director-python-plugin
```

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  filedaemon-python-plugin
```suggestion
Provides:   bareos-filedaemon-python-plugin
Obsoletes:  bareos-filedaemon-python-plugin
```

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  storage-python-plugin
```suggestion
Provides:   bareos-storage-python-plugin
Obsoletes:  bareos-storage-python-plugin
```

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  filedaemon-python-plugin
```suggestion
Provides:   bareos-filedaemon-python-plugin
Obsoletes:  bareos-filedaemon-python-plugin
```

2020-10-05 09:15 UTC, arogge commented on core/platforms/packaging/bareos.spec
> +Obsoletes:  storage-python-plugin
```suggestion
Provides:   bareos-storage-python-plugin
Obsoletes:  bareos-storage-python-plugin
```

2020-10-05 09:45 UTC, arogge commented
I tested the installation on Debian 10. The python2 plugin package is preferred there. This is probably true for all other Debian-based distro's, too.

2020-10-15 09:42 UTC, merged