adapt oVirt plugin for python3
bareos/bareos pull request #665
Opened 2020-11-11 15:57 UTC by pstorz

2020-12-01 16:21 UTC, sduehr commented
As of https://bugzilla.redhat.com/show_bug.cgi?id=1862722 the use of "ImageTransfer.signed_ticket"
is not necessary since oVirt 4.2. Removed it and verified that it work without also when using oVirt SDK 4.2 and 4.3.
Pushed the changed code.

Remaining Problem:
When using non-ascii characters in disk alias name, with Python 2 the backup fails with
```
  File "/home/stephand/github/bareos/core/src/plugins/filed/python/pyfiles/BareosFdWrapper.py", line 42, in start_backup_file
    return bareos_fd_plugin_object.start_backup_file(savepkt)
  File "/home/stephand/github/bareos/core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py", line 182, in start_backup_file
    self.backup_obj["file"]["fh"] = io.BytesIO(vmfile["data"].encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1568: ordinal not in range(128)

```

and with Python 3 the restore fails with
```

01-Dec 14:58 py3plug-fd-ovirt-fd JobId 2: Fatal error: bareosfd: Traceback (most recent call last):
  File "/home/stephand/github/bareos/core/src/plugins/filed/python/pyfiles/BareosFdWrapper.py", line 66, in create_file
    return bareos_fd_plugin_object.create_file(restorepkt)
  File "/home/stephand/github/bareos/core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py", line 302, in create_file
    if not os.path.exists(dirname):
  File "/usr/lib64/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 107: ordinal not in range(128)
```

2020-12-15 00:21 UTC, sduehr requested changes
I've recently pushed my suggested changes and fixes, they should be reviewed by somebody else, please.

2020-12-15 09:55 UTC, arogge commented on core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
> +                "Please install the Python SDK for oVirt Engine API.\n",
That message doesn't tell me what package to get from pip. Maybe we should mention `pyvmomi` here?

2020-12-15 11:29 UTC, pstorz reviewed
Are these indentations intentionally there?

2020-12-15 11:29 UTC, pstorz commented on core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
>              "   Transfer disk snapshot of %s bytes\n" % (str(self.bytes_to_transf)),
```suggestion
            "Transfer disk snapshot of %s bytes\n" % (str(self.bytes_to_transf)),
```

2020-12-15 11:29 UTC, pstorz commented on core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
>              "   Upload disk of %s bytes\n" % (str(self.bytes_to_transf)),
```suggestion
            "Upload disk of %s bytes\n" % (str(self.bytes_to_transf)),
```

2020-12-15 11:35 UTC, pstorz commented on core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
>              "   Upload disk of %s bytes\n" % (str(self.bytes_to_transf)),
It is intentionally indented

2020-12-15 11:38 UTC, merged