python-bareos: extends the documentation
bareos/bareos pull request #704
Opened 2021-01-07 11:18 UTC by joergsteffens

This PR contains

- some general DeveloperGuide fixes,
- add a note about Python docstring formating,
- updates python-bareos  README file and its docstrings,
- add python-bareos to DeveloperGuide (by extracting doctrings via Sphinx extension autosummary).

2021-01-28 14:08 UTC, arogge requested changes
The content looks great overall, some of the commits were in 2021 and need a more recent year in the copyright notice. Also the integration of the autosummary into the hierarchy is broken (i.e. it is located under "Exmaple")

2021-01-28 14:12 UTC, joergsteffens commented on docs/manuals/source/DeveloperGuide/api.rst
> +   all begin with a period and provide things such as the list of all
We decided, that comma before "and" and "or" are not required.

2021-01-28 14:13 UTC, joergsteffens commented on docs/manuals/source/DeveloperGuide/PythonBareos.rst
> +   bareos.bsock.bsockjson
This is a commented section. See ".. " above

2021-01-28 18:41 UTC, joergsteffens commented on docs/manuals/source/DeveloperGuide/PythonBareos.rst
> +   bareos.bsock.bsockjson
I see, the comment marker misses the trailing space. I fixed this in additional commit.

2021-01-28 18:42 UTC, joergsteffens commented on docs/manuals/source/DeveloperGuide/PythonBareos.rst
> +.. autosummary::
I modified it.

2021-01-29 14:18 UTC, arogge approved these changes

2021-01-29 14:21 UTC, merged