disable recent job results list for sparc and improve test
bareos/bareos pull request #758
Opened 2021-03-02 16:34 UTC by franku

- rename test "recently-used-jobs" to "statefile"
- disable all "statefile" tests for sparc
- use temporary state files instead of original files in the source code which may be deleted during the test in case of an error

#### Checklist
- [x] [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [x] [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [x] [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

#### Add some information

- [x] Add a small description to the CHANGELOG.md file and refer to your PR using this syntax '[PR #xyz]'
- [x] Add your name to the AUTHORS file

#### Keep spirit!
- [x] Do not be afraid to hand in a PR!

2021-03-03 12:29 UTC, arogge requested changes
the code doesn't build on the  stock rhel 7 compiler, but I think it should (or we should require a newer compiler)

2021-03-03 13:11 UTC, franku commented on core/src/tests/CMakeLists.txt
>  # set some path variables used during test compilation
The change somehow disappeard. I know that I ran check-sources. Will correct that.

2021-03-03 13:11 UTC, franku commented on core/src/tests/statefile.cc
> +  auto recent_jobs{RecentJobResultsList::Get()};
Will correct that for 20.

2021-03-11 16:21 UTC, arogge approved these changes

2021-03-11 16:30 UTC, merged