fix for configure add storage description missing quotes
bareos/bareos pull request #764
Opened 2021-03-12 13:30 UTC by alaaeddineelamri

2021-03-23 16:10 UTC, pstorz commented on core/src/dird/ua_configure.cc
> +  const std::vector<int> quotable_types{
Why not use a std::array here? The size is fixed and will not be altered so std::array is the better option I guess.

2021-03-24 15:04 UTC, joergsteffens commented on systemtests/tests/python-bareos/python-bareos-unittest.py
> +        """"""
```suggestion
```

2021-03-24 15:04 UTC, joergsteffens commented on systemtests/tests/python-bareos/python-bareos-unittest.py
> +        """"""
```suggestion
```

2021-03-24 16:07 UTC, joergsteffens approved these changes
Looks good. Automatic and manual testing succeeded.

2021-03-24 16:19 UTC, joergsteffens requested changes
Unfortenatly I see now, that compilation fails on some platforms, namely:

* Debian_9.0.i586
* Debian_9.0.x86_64
* Univention_4.4.x86_64 (might also be based on Debian 9)
* FreeBSD_12.2.amd64

The error always looks similar to this:

```
[2021-03-24T15:33:33.312Z] ../../../../core/src/dird/ua_configure.cc: In function ‘bool directordaemon::config_add_directive(directordaemon::UaContext*, ResourceTable*, const char*, const char*, PoolMem&, int)’:

[2021-03-24T15:33:33.312Z] ../../../../core/src/dird/ua_configure.cc:142:9: error: invalid use of template-name ‘std::array’ without an argument list

[2021-03-24T15:33:33.312Z]    const std::array quotable_types{

[2021-03-24T15:33:33.312Z]          ^~~

[2021-03-24T15:33:33.312Z] In file included from /usr/include/c++/6/tuple:39:0,

[2021-03-24T15:33:33.312Z]                  from /usr/include/c++/6/bits/stl_map.h:63,

[2021-03-24T15:33:33.312Z]                  from /usr/include/c++/6/map:61,

[2021-03-24T15:33:33.312Z]                  from ../../../../core/src/include/bareos.h:184,

[2021-03-24T15:33:33.312Z]                  from ../../../../core/src/dird/ua_configure.cc:29:

[2021-03-24T15:33:33.312Z] /usr/include/c++/6/array:90:12: note: ‘template<class _Tp, unsigned int _Nm> struct std::array’ declared here
```

2021-03-29 15:00 UTC, joergsteffens approved these changes

2021-04-01 07:35 UTC, merged