Updated localization
bareos/bareos pull request #776
Opened 2021-03-26 12:24 UTC by fbergkemper

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-04-01 09:59 UTC, pstorz requested changes
There are some words not translated into german. I guess this is intentionally?

2021-04-01 09:59 UTC, pstorz commented on webui/module/Application/language/de_DE.po
> +msgstr "A 404 error occurred"
```suggestion
msgstr "Ein Fehler ist aufgetreten (404)"
```

2021-04-01 09:59 UTC, pstorz commented on webui/module/Application/language/de_DE.po
> -msgstr "vorige Ausnahmen"
Why is the translation reverted?

2021-04-01 09:59 UTC, pstorz commented on webui/module/Application/language/de_DE.po
> +msgstr "Manage Medienwechsler"
```suggestion
msgstr "Medienwechsler verwalten"
```

2021-04-01 11:37 UTC, fbergkemper commented on webui/module/Application/language/de_DE.po
> +msgstr "A 404 error occurred"
Applied

2021-04-01 11:37 UTC, fbergkemper commented on webui/module/Application/language/de_DE.po
> +msgstr "Manage Medienwechsler"
Applied

2021-04-01 11:38 UTC, fbergkemper commented on webui/module/Application/language/de_DE.po
> -msgstr "vorige Ausnahmen"
Mistake, changed it.

2021-04-01 11:39 UTC, fbergkemper commented
> 
> 
> There are some words not translated into german. I guess this is intentionally?

Yes, mostly those ones are error message, which we may or may not translate in future.

2021-04-06 09:26 UTC, pstorz approved these changes
Looks good.

2021-04-06 09:31 UTC, merged