fix py save packet memleak
bareos/bareos pull request #784
Opened 2021-04-01 15:45 UTC by pstorz

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-04-21 19:15 UTC, franku reviewed
Would suggest to use const char* and strdup because it is not plausible to use a std::string on the heap here.

2021-04-21 19:15 UTC, franku commented on core/src/lib/message_queue_item.h
> +  std::string* msg_{nullptr};
```suggestion
  const char* msg_{nullptr};
```

2021-04-21 19:15 UTC, franku commented on core/src/lib/message.cc
> +  item->msg_ = new std::string(buf.c_str());
```suggestion
  item->msg_ = strdup(buf.c_str());
```

2021-04-21 19:15 UTC, franku commented on core/src/lib/message.cc
> +    syslog(LOG_DAEMON | LOG_ERR, "%s", item->msg_->c_str());
```suggestion
    syslog(LOG_DAEMON | LOG_ERR, "%s", item->msg_);
```

2021-04-21 19:15 UTC, franku commented on core/src/lib/message.cc
> +    delete item->msg_;
```suggestion
    free(item->msg_);
    item->msg_ = nullptr;
```

2021-04-21 19:15 UTC, franku commented on core/src/lib/message.cc
> +    delete (item->msg_);
```suggestion
    free(item->msg_);
    item->msg_ = nullptr;
```

2021-05-27 08:49 UTC, sduehr requested changes
Looks good now, ready for merge, only CHANGELOG.md entry is missing.

2021-05-27 15:41 UTC, arogge requested changes
If it isn't `const` to us, we shouldn't delcare it `const`
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es50-dont-cast-away-const

2021-05-27 15:41 UTC, arogge commented on core/src/lib/message.cc
> +    free(const_cast<char*>(item->msg_));
```suggestion
    free(item->msg_);
```

2021-05-27 15:41 UTC, arogge commented on core/src/lib/message.cc
> +    free(const_cast<char*>(item->msg_));
```suggestion
    free(item->msg_);
```

2021-05-27 15:41 UTC, arogge commented on core/src/lib/message_queue_item.h
> +  const char* msg_{nullptr};
```suggestion
  char* msg_{nullptr};
```

2021-05-30 14:53 UTC, merged