webui: close socket on fwrite() error
bareos/bareos pull request #840
Opened 2021-06-10 11:50 UTC by fbergkemper

fwrite() returns the number of bytes written, or false on error.

Fixes #1324: Infinite loop when trying to log with invalid account

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-06-21 10:13 UTC, pstorz requested changes
Looks good, but it makes sense to change the title of the bug, and the commit message to have the correct sentence.

2021-06-21 10:13 UTC, pstorz commented on CHANGELOG.md
> +- [Issue #1324]: Infinite loop when trying to log with invalid account [PR #840]
```suggestion
- [Issue #1324]: Infinite loop when trying to log in with invalid account [PR #840]
```

2021-06-21 10:31 UTC, fbergkemper commented
> 
> 
> Looks good, but it makes sense to change the title of the bug, and the commit message to have the correct sentence.

Commit message reworded.

2021-06-21 10:31 UTC, fbergkemper commented on CHANGELOG.md
> +- [Issue #1324]: Infinite loop when trying to log with invalid account [PR #840]
Requested change applied.

2021-06-28 11:52 UTC, pstorz approved these changes
Looks good to me. Good Work

2021-06-28 12:34 UTC, merged