webui: provide a better error message on login failure
bareos/bareos pull request #853
Opened 2021-06-16 12:13 UTC by fbergkemper

The error message on login failure should give a hint
when you try to login with a console user having the
"TLS Enable = false" parameter not set.

Fixes #1096: misleading error message

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-06-21 09:58 UTC, arogge commented on webui/module/Auth/src/Auth/Controller/AuthController.php
> +         $err_msg = "Sorry, can not authenticate. Wrong username and password or SSL/TLS handshake failed.";
```suggestion
         $err_msg = "Sorry, cannot authenticate. Wrong username, password or SSL/TLS handshake failed.";
```

2021-06-21 10:19 UTC, fbergkemper commented on webui/module/Auth/src/Auth/Controller/AuthController.php
> +         $err_msg = "Sorry, can not authenticate. Wrong username and password or SSL/TLS handshake failed.";
Requested change applied.

2021-06-28 12:56 UTC, arogge requested changes
The header needs to be changed, it still sais 2020.
You may also want to mention the change in the changelog.

2021-06-28 13:04 UTC, fbergkemper commented
> The header needs to be changed, it still sais 2020.

Right, I changed it.

> You may also want to mention the change in the changelog.

Too tiny, there are more important things to mention.

2021-06-28 13:09 UTC, arogge approved these changes

2021-06-28 13:10 UTC, merged