Merge Windows Debug-Build into Release-Build
bareos/bareos pull request #858
Opened 2021-06-22 13:56 UTC by arogge

As the difference between debug and release for Windows is the shipping of the sourcecode only, this PR merges both packages into one.
The Sourcecode is now an optional component that can be selected at install-time.

To reconfigure the builds, this PR also adds a .matrix.yml that will tell Jenkins to only do the release-builds in the future.

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

2021-06-22 14:26 UTC, pstorz requested changes
The matrix.yml file is not correct.

2021-06-22 14:26 UTC, pstorz commented on .matrix.yml
> +    "4.4":
I think here is something missing, probably 
**Univention:**

2021-06-22 17:05 UTC, pstorz requested changes
I think it makes sense to add a line to the CHANGELOG that the two windows builds were merged and only one Installer is now available for windows 32 and for windows 64.

2021-06-24 17:29 UTC, arogge commented
I triple-checked that all distros are built, all files are still produced as desired (i.e. no webui tarballs) and added the CHANGELOG record you requested.

2021-06-28 14:33 UTC, pstorz approved these changes
Good work, looks good to me. You might want to squash the last two commits.

2021-06-28 15:05 UTC, merged