core: improve mtx-changer debug output
bareos/bareos pull request #897
Opened 2021-08-02 07:42 UTC by fbergkemper

Log the drive status in wait_for_drive().

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-08-05 13:53 UTC, pstorz requested changes
I think '$1' should be quoted before it gets passed to mt, and the debug output saying that the mt -f $1 is being done also should be printed when it is really done.

2021-08-05 13:53 UTC, pstorz commented on core/scripts/mtx-changer.in
> +    debug "Doing mt -f $1 status ..."
```suggestion
```

2021-08-05 13:53 UTC, pstorz commented on core/scripts/mtx-changer.in
> +    drivestatus=$(mt -f $1 status 2>&1)
```suggestion
    debug "Doing mt -f $1 status ..."
    drivestatus=$(mt -f "$1" status 2>&1)
```

2021-08-05 14:35 UTC, fbergkemper commented on core/scripts/mtx-changer.in
> +    drivestatus=$(mt -f $1 status 2>&1)
change request applied

2021-08-10 08:34 UTC, pstorz approved these changes

2021-08-10 08:34 UTC, merged