cleanup: add missing \n in Jmsg calls where missing
bareos/bareos pull request #964
Opened 2021-10-22 15:00 UTC by pstorz

### Thank you for contributing to the Bareos Project!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] `bareos-check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

2021-11-05 12:32 UTC, sduehr requested changes
Some of the added `\n` are not needed.

2021-11-05 12:32 UTC, sduehr commented on core/src/stored/label.cc
> +        Jmsg(jcr, M_FATAL, 0, _("Too many tries: %s\n"), jcr->errmsg);
```suggestion
        Jmsg(jcr, M_FATAL, 0, _("Too many tries: %s"), jcr->errmsg);
```
`jcr->errmsg` already contains `\n`

2021-11-05 12:32 UTC, sduehr commented on core/src/stored/label.cc
> +      Jmsg(jcr, M_FATAL, 0, _("Too many tries: %s\n"), jcr->errmsg);
```suggestion
      Jmsg(jcr, M_FATAL, 0, _("Too many tries: %s"), jcr->errmsg);
```
same here

2021-11-05 12:32 UTC, sduehr commented on core/src/stored/label.cc
> +      Jmsg(jcr, M_FATAL, 0, "Too many tries: %s\n", jcr->errmsg);
```suggestion
      Jmsg(jcr, M_FATAL, 0, "Too many tries: %s", jcr->errmsg);
```
same here

2021-11-05 12:32 UTC, sduehr commented on core/src/stored/mount.cc
> +               "    %s\n"),
```suggestion
               "    %s"),
```
`CatalogRequest()` already add `\n` to such messages

2021-11-09 13:03 UTC, pstorz reviewed
Thank you for reviewing!

2021-11-10 10:50 UTC, sduehr approved these changes
Thanks, looks good now.

2021-11-10 10:57 UTC, merged