Fix libdroplet xattr.h include
bareos/bareos pull request #985
Opened 2021-11-15 10:38 UTC by bruno-at-bareos

This PR update the way xattr.h is included in libdroplet by removing obsolete attr/xattr.h include.
see 2015 attr upstream commit https://git.savannah.nongnu.org/cgit/attr.git/commit/?id=7921157890d07858d092f4003ca4c6bae9fd2c38 and replace by sys/xattr.h

### Thank you for contributing to the Bareos Project!

#### Please check

- [ ] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

2021-11-16 07:59 UTC, pstorz requested changes
Unfortunately, these changes do not build on CentOS7:


[2021-11-15T10:57:33.677Z] In file included from ../../../../../core/src/droplet/libdroplet/src/utils.c:36:
[2021-11-15T10:57:33.677Z] /usr/include/sys/xattr.h:31:3: error: expected identifier before numeric constant
[2021-11-15T10:57:33.677Z]    XATTR_CREATE = 1, /* set value, fail if attr already exists.  */
[2021-11-15T10:57:33.677Z]    ^~~~~~~~~~~~

2021-11-16 08:15 UTC, bruno-at-bareos commented
> Unfortunately, these changes do not build on CentOS7:
> 
> [2021-11-15T10:57:33.677Z] In file included from ../../../../../core/src/droplet/libdroplet/src/utils.c:36: [2021-11-15T10:57:33.677Z] /usr/include/sys/xattr.h:31:3: error: expected identifier before numeric constant [2021-11-15T10:57:33.677Z] XATTR_CREATE = 1, /* set value, fail if attr already exists. */ [2021-11-15T10:57:33.677Z] ^~~~~~~~~~~~

I've seen yesterday night, I've somewhat forget how rhel7 is archeological with a libc 2.17 and a 3x kernel :-)
I guess I will go to #ifdef path...

2021-11-17 09:10 UTC, bruno-at-bareos reviewed
Seems we are not good.

2021-11-18 11:33 UTC, pstorz approved these changes
Very good and short solution

2021-11-18 11:33 UTC, merged